Repository canonical/canonical.com, pull requests merged in 2019-12, with the labels that each got.

#115 Add office addresses to the contact page
  static/sass/styles.scss
  templates/contact-us.html
  templates/partial/_navigation.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#119 Add dockerfile to project
  Dockerfile
Labels: Review: Code +1, Review: QA +1

#120 Nav updates
  static/js/highlight-nav-on-scroll.js
  static/js/navigation.js
  static/sass/_pattern_navigation.scss
  templates/index.html
  templates/partial/_navigation.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#121 Copy updates
  templates/careers/_secondary-navigation.html
  templates/careers/commercial-ops.html
  templates/careers/design.html
  templates/careers/hr.html
  templates/careers/index.html
  templates/careers/results.html
  templates/partial/_careers-navigation.html
  templates/partial/_navigation-careers.html
Labels: Review: Code +1 (with changes), Review: QA +1

#122 Parse the feed departments to work with the site
  tests/test_greenhouse_api.py
  webapp/greenhouse_api.py
Labels: Review: Code +1, Review: QA +1

#131 increase padding on nav on x-small screens
  static/sass/_pattern_navigation.scss
Labels: Review: Code +1, Review: QA +1
