Repository canonical/canonical.com, pull requests merged in 2019-10, with the labels that each got.

#47 Add partners/kubernetes page
  static/sass/_pattern_cards.scss
  static/sass/_pattern_strip.scss
  templates/careers/travel.html
  templates/partners/kubernetes.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#48 Implement initial basic navigation
  static/sass/_pattern_navigation.scss
  static/sass/styles.scss
  templates/base.html
  templates/partners/become-a-partner.html
  webapp/app.py
Labels: Review: Code +1, Review: QA +1

#50 1771 build partners page
  static/sass/_pattern_media-object.scss
  static/sass/styles.scss
  templates/partial/_partners-footer.html
  templates/partners/index.html
  templates/partners/kubernetes.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#49 1766 partners desktop page
  templates/partial/_partners-footer.html
  templates/partners/desktop.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#51 Partners cloud
  static/sass/styles.scss
  templates/partners/cloud.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#46 Add filter and search to find-a-partner page
  requirements.txt
  static/js/find-a-partner.js
  static/sass/_pattern_buttons.scss
  static/sass/styles.scss
  templates/partners/find-a-partner.html
  webapp/app.py
  webapp/partners_api.py
Labels: Review: Code +1, Review: QA +1

#45 1658 link game to jobs page
  static/js/careers-filter&sort.js
  static/js/careers-game.js
  static/sass/_pattern_forms.scss
  templates/careers/careers_base.html
  templates/careers/results.html
  templates/careers/start.html
  templates/partial/_careers-available-roles.html
  webapp/app.py
  webapp/greenhouse_api.py
Labels: Review: Code +1, Review: QA +1

#60 Add redirects from the old pages to new
  redirects.yaml
Labels: Review: Code +1, Review: QA +1

#57 Mega menu navigation
  static/js/navigation.js
  static/sass/_pattern_navigation.scss
  static/sass/_pattern_strip.scss
  static/sass/styles.scss
  templates/base.html
  templates/careers/_secondary-navigation.html
  templates/partial/_navigation-careers.html
  templates/partial/_navigation-partners.html
  templates/partial/_navigation-products.html
  templates/partial/_navigation.html
  templates/partners/_secondary-navigation.html
  webapp/app.py
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#61 Change job application form on /careers/<department>
  static/js/apply-for-jobs.js
  static/js/file-validation.js
  static/sass/_pattern_forms.scss
  templates/careers/careers_base.html
  templates/careers/job-detail.html
  templates/careers/jobs/job-detail.html
  templates/careers/results.html
  templates/partial/_careers-available-roles.html
  templates/partial/_careers-send-cv.html
  webapp/app.py
  webapp/greenhouse_api.py
Labels: Review: Code +1, Review: QA +1

#62 Add empty state for careers pages
  templates/partial/_careers-available-roles.html
Labels: Review: Code +1, Review: QA +1

#63 Add functionality to /partners/become-a-partner
  static/js/careers-game.js
  static/sass/_pattern_buttons.scss
  static/sass/_pattern_cards.scss
  templates/careers/start.html
  templates/partial/_careers-available-roles.html
  templates/partners/become-a-partner.html
  templates/partners/find-a-partner.html
  webapp/greenhouse_api.py
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#66 Add ids to products, partners & careers sections
  static/js/careers-game.js
  static/js/dynamic-image-load.js
  static/js/navigation.js
  static/sass/_pattern_buttons.scss
  static/sass/_pattern_cards.scss
  templates/careers/results.html
  templates/index.html
  templates/partial/_navigation.html
  webapp/app.py
Labels: Review: Code +1, Review: QA +1

#67 Add careers filters to the url
  static/js/careers-filter&sort.js
  static/js/careers-filter-and-sort.js
  templates/careers/careers_base.html
  templates/partial/_careers-available-roles.html
  templates/partners/find-a-partner.html
Labels: Review: Code +1, Review: QA +1

#68 Add ids to the navigation tabs on careers pages
  templates/careers/careers_base.html
Labels: Review: Code +1, Review: QA +1

#64 Add Python testing infrastructure
  .circleci/config.yml
  README.md
  package.json
  run
  tests/__init__.py
  tests/test_routes.py
Labels: Review: Code +1, Review: QA +1
