Repository canonical/canonical.com, pull requests merged in 2019-06, with the labels that each got.

#2 Create skeleton Flask app
  .env
  .gitignore
  README.md
  entrypoint
  package.json
  requirements.txt
  run
  static/sass/styles.scss
  templatefinder/README.md
  templatefinder/__init__.py
  templatefinder/poetry.lock
  templatefinder/pyproject.toml
  templatefinder/templatefinder.py
  templatefinder/tests/__init__.py
  templatefinder/tests/fixtures/index.html
  templatefinder/tests/fixtures/markdown_wrapper.html
  templatefinder/tests/fixtures/nested/index.html
  templatefinder/tests/fixtures/nested/test.md
  templatefinder/tests/fixtures/test-missing-wrapper-file.md
  templatefinder/tests/fixtures/test-missing-wrapper.md
  templatefinder/tests/fixtures/test.md
  templatefinder/tests/test_templatefinder.py
  templates/404.html
  templates/500.html
  templates/index.html
  templates/partial/markdown_wrapper.html
  templates/test.md
  webapp/app.py
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#7 Add CircleCI tests; fixup package.json scripts
  .circleci/config.yml
  package.json
Labels: Review: Code needed, Review: QA needed

#8 Add correct port number
  README.md
Labels: Review: Code +1

#9 Use the templatefinder module from GitHub
  package.json
  requirements.txt
  templatefinder/README.md
  templatefinder/__init__.py
  templatefinder/poetry.lock
  templatefinder/pyproject.toml
  templatefinder/templatefinder.py
  templatefinder/tests/__init__.py
  templatefinder/tests/fixtures/index.html
  templatefinder/tests/fixtures/markdown_wrapper.html
  templatefinder/tests/fixtures/nested/index.html
  templatefinder/tests/fixtures/nested/test.md
  templatefinder/tests/fixtures/test-missing-wrapper-file.md
  templatefinder/tests/fixtures/test-missing-wrapper.md
  templatefinder/tests/fixtures/test.md
  templatefinder/tests/test_templatefinder.py
  webapp/app.py
Labels: Review: Code +1, Review: QA +1

#11 Bump flask-base to 0.3.1
  requirements.txt
  webapp/app.py
Labels: Review: Code +1, Review: QA +1
