Repository canonical/canonical.com, pull requests merged in 2019-11, with the labels that each got.

#70 Change python tests CircleCI endpoint to match the package.json endpoint
  .circleci/config.yml
Labels: Review: Code +1

#87 Update /contact-us page
  templates/base.html
  templates/contact-us.html
Labels: Review: Code +1, Review: QA +1

#88 Remove partners from the navigation
  .github/pull_request_template.md
  templates/partial/_navigation.html
Labels: Review: Code +1, Review: QA +1

#89 Update /careers/all page
  templates/careers/all.html
Labels: Review: Code +1, Review: QA +1

#90 Update /careers/design page
  templates/base.html
  templates/careers/all.html
  templates/careers/design.html
  templates/partial/_careers-available-roles.html
Labels: Review: Code +1, Review: QA +1

#94 Update /careers/project-management page
  templates/careers/project-management.html
Labels: Review: Code +1, Review: QA +1

#91 81 update careers engineering
  templates/careers/design.html
  templates/careers/engineering.html
Labels: Review: Code +1, Review: QA +1

#93 83 update careers hr
  templates/careers/hr.html
Labels: Review: Code +1, Review: QA +1

#96 Update /careers/sales page
  templates/careers/sales.html
Labels: Review: Code +1, Review: QA +1

#97 Update circleci shield style
  README.md
Labels: Review: Code +1

#99 Update the careers overview page content
  templates/careers/index.html
Labels: Review: Code +1, Review: QA +1

#100 Fix commercial-ops and admin link in the nav
  templates/careers/_secondary-navigation.html
  templates/careers/index.html
  templates/partial/_navigation-careers.html
Labels: Review: Code +1, Review: QA +1

#101 Update the home page content
  templates/index.html
Labels: Review: Code +1, Review: QA +1

#104 Update job list to match new design
  templates/careers/careers_base.html
  templates/partial/_careers-available-roles.html
  templates/partial/_careers-navigation.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#102 Show default partners on home page
  templates/index.html
Labels: Review: Code +1, Review: Design +1

#106 Update product links in the navigation
  templates/partial/_navigation-products.html
Labels: Review: Code +1, Review: QA +1

#110 86 update careers techops
  templates/careers/admin.html
  templates/careers/all.html
  templates/careers/commercial-ops.html
  templates/careers/design.html
  templates/careers/diversity.html
  templates/careers/engineering.html
  templates/careers/ethics.html
  templates/careers/finance.html
  templates/careers/hr.html
  templates/careers/legal.html
  templates/careers/lifestyle.html
  templates/careers/marketing.html
  templates/careers/progression.html
  templates/careers/project-management.html
  templates/careers/sales.html
  templates/careers/tech-ops.html
  templates/careers/travel.html
Labels: Review: Code +1, Review: QA +1

#111 Update the default application job number
  webapp/greenhouse_api.py
Labels: Review: Code +1

#109 Hide overview tab on /careers/all and add 404 & 500 pages
  static/js/navigation.js
  static/sass/_pattern_navigation.scss
  static/sass/styles.scss
  templates/404.html
  templates/500.html
  templates/base.html
  templates/careers/_secondary-navigation.html
  templates/careers/careers_base.html
  templates/partial/_careers-available-roles.html
  templates/partial/_careers-navigation.html
  templates/partial/_navigation.html
  templates/partial/markdown_wrapper.html
  templates/test.md
Labels: Review: Code +1, Review: Design +1, Review: QA +1
