Repository canonical/canonical.com, pull requests merged in 2020-01, with the labels that each got.

#136 Tabs refactor
  static/js/tabs.js
  static/sass/_pattern_tabs.scss
  static/sass/styles.scss
  templates/404.html
  templates/500.html
  templates/base_index.html
  templates/careers/admin.html
  templates/careers/all.html
  templates/careers/apply.html
  templates/careers/base-tabs.html
  templates/careers/base.html
  templates/careers/careers_base.html
  templates/careers/commercial-ops.html
  templates/careers/design.html
  templates/careers/diversity.html
  templates/careers/engineering.html
  templates/careers/ethics.html
  templates/careers/finance.html
  templates/careers/hr.html
  templates/careers/index.html
  templates/careers/job-detail.html
  templates/careers/legal.html
  templates/careers/lifestyle.html
  templates/careers/marketing.html
  templates/careers/progression.html
  templates/careers/project-management.html
  templates/careers/results.html
  templates/careers/sales.html
  templates/careers/start.html
  templates/careers/tech-ops.html
  templates/careers/travel.html
  templates/contact-us.html
  templates/index.html
  templates/partial/_careers-available-roles.html
  templates/partial/_careers-job-list.html
  templates/partial/_careers-navigation.html
  templates/partial/_careers-send-cv.html
  templates/partners/apps-and-snaps.html
  templates/partners/become-a-partner.html
  templates/partners/cloud.html
  templates/partners/desktop.html
  templates/partners/devices-and-iot.html
  templates/partners/find-a-partner.html
  templates/partners/index.html
  templates/partners/kubernetes.html
Labels: Review: Code +1 (with changes), Review: QA +1

#138 Fix filters on results
  static/js/careers-filter-and-sort.js
  templates/careers/_filters.html
  templates/careers/base.html
  templates/careers/results.html
  templates/partial/_careers-available-roles.html
  templates/partial/_careers-job-list.html
Labels: Review: Code +1, Review: QA +1

#139 replace large file size images with optimised versions
  templates/careers/index.html
  templates/careers/lifestyle.html
  templates/careers/travel.html
Labels: Review: Design +1

#141 Fix /careers/results
  static/js/apply-for-jobs.js
  static/js/modal.js
  static/sass/_pattern_careers-modal.scss
  templates/careers/_vacancies-modal.html
  templates/careers/apply.html
  templates/careers/base-tabs.html
  templates/careers/results.html
  templates/partial/_careers-job-list.html
  templates/partial/_careers-modal.html
  webapp/greenhouse_api.py
Labels: Review: Code +1, Review: QA +1

#142 Set explicit list of careers department routes
  tests/test_routes.py
  webapp/app.py
Labels: Review: Code +1, Review: QA +1

#143 remove "send your cv" tab
  templates/careers/base-tabs.html
  templates/partial/_careers-available-roles.html
  webapp/app.py
Labels: Review: Code +1, Review: QA +1

#144 Fix missing "no results" message when filtering job results
  templates/careers/results.html
Labels: Review: Code +1, Review: QA +1

#145 Multistage build
  Dockerfile
  package.json
Labels: Review: Code +1, Review: QA +1

#146 Add redirects to map the current pages to useful pages
  redirects.yaml
Labels: Review: Code +1, Review: QA +1

#148 Scott's post-launch fixes for Peter's pre-launch snags
  static/sass/_pattern_footer.scss
  templates/careers/index.html
  templates/index.html
  templates/partial/_careers-job-list.html
  templates/partial/_footer.html
Labels: Review: Code +1, Review: QA +1

#150 Add redirect for projects directory
  redirects.yaml
Labels: Review: Code +1, Review: QA +1

#154 Fix tech ops available job view
  webapp/app.py
Labels: Review: Code +1, Review: QA +1

#156 A better fix for techops roles
  webapp/app.py
Labels: Review: Code needed, Review: QA needed

#158 Add social metadata to base + careers/start page
  templates/base_index.html
  templates/careers/start.html
  templates/partners/become-a-partner.html
Labels: Review: Code +1, Review: QA +1

#160 Add missing row of departments to /careers
  templates/careers/index.html
Labels: Review: Code +1, Review: QA +1

#161 Add missing meta data to pages
  templates/404.html
  templates/500.html
  templates/careers/admin.html
  templates/careers/all.html
  templates/careers/apply.html
  templates/careers/commercial-ops.html
  templates/careers/design.html
  templates/careers/diversity.html
  templates/careers/engineering.html
  templates/careers/ethics.html
  templates/careers/finance.html
  templates/careers/hr.html
  templates/careers/index.html
  templates/careers/job-detail.html
  templates/careers/legal.html
  templates/careers/lifestyle.html
  templates/careers/marketing.html
  templates/careers/progression.html
  templates/careers/project-management.html
  templates/careers/results.html
  templates/careers/sales.html
  templates/careers/start.html
  templates/careers/tech-ops.html
  templates/careers/travel.html
  templates/contact-us.html
Labels: Review: Code needed, Review: QA needed

#164 Add redirect from /index.html
  redirects.yaml
Labels: Review: Code needed, Review: QA needed

#163 Add check for job id
  webapp/app.py
  webapp/greenhouse_api.py
Labels: Review: Code +1, Review: QA +1

#166 GA events clean-up
  static/js/navigation.js
Labels: Review: Code +1, Review: QA +1

#167 Fix missing spaces in HTML attributes
  templates/index.html
Labels: Review: Code +1, Review: QA +1

#171 Support disabling reduced motion
  static/sass/_pattern_animations.scss
Labels: Review: Code +1, Review: QA +1

#173 refactor careers game
  static/js/careers-game.js
  static/sass/_pattern_buttons.scss
  static/sass/_pattern_cards.scss
  templates/careers/_skill.html
  templates/careers/_skills.html
  templates/careers/start.html
Labels: Review: Code +1, Review: QA +1

#175 Add versioned_static to cache bust local assets
  templates/base_index.html
Labels: Review: Code +1, Review: QA +1

#174 Add rediect from contributors
  redirects.yaml
Labels: Review: Code +1, Review: QA +1
