Repository canonical/canonical.com, pull requests merged in 2020-09, with the labels that each got.

#273 Add dynamic navigation to careers page
  .circleci/config.yml
  konf/site.yaml
  package.json
  requirements.txt
  templates/502.html
  templates/careers/base-template.html
  templates/partial/_careers-navigation.html
  tests/cassettes/TestRoutes.test_careers_department.yaml
  tests/cassettes/TestRoutes.test_homepage.yaml
  tests/cassettes/TestRoutes.test_invalid_careers_department.yaml
  tests/cassettes/TestRoutes.test_partners_detail_pages.yaml
  tests/test_routes.py
  webapp/app.py
  webapp/greenhouse.py
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#276 Reduce parsing of department fields
  templates/careers/human-resources.html
  templates/careers/operations.html
  templates/careers/techops.html
  templates/careers/web-and-design.html
  webapp/app.py
  webapp/greenhouse.py
Labels: Review: Code +1, Review: QA +1

#279 Update the links based on the data source
  redirects.yaml
  templates/careers/_secondary-navigation.html
  templates/careers/index.html
  templates/partial/navigation-careers.html
Labels: Review: Code +1, Review: QA +1

#282 Update flask-base
  requirements.txt
Labels: Review: Code +1, Review: QA +1

#286 Change GTM tag
  templates/base_index.html
Labels: Review: Code +1, Review: QA +1

#288 Use webteam default renovate config
  renovate.json
Labels: Review: Code +1

#291 Add new cookie policy module
  package.json
  static/js/modules/cookie-policy/cookie-policy.js
  static/sass/styles.scss
  templates/base_index.html
  templates/partial/_footer.html
  yarn.lock
Labels: Review: Code +1, Review: QA +1
