Repository canonical/canonical.com, pull requests merged in 2020-04, with the labels that each got.

#197 Update page title
  templates/base_index.html
Labels: Review: Code +1, Review: QA +1

#195 Replace canonicalwebteam.http with Talisker session
  .env
  .gitignore
  README.md
  entrypoint
  package.json
  requirements.txt
  tests/test_greenhouse.py
  tests/test_routes.py
  webapp/app.py
  webapp/greenhouse.py
  webapp/greenhouse_api.py
  webapp/partners.py
  webapp/partners_api.py
  yarn.lock
Labels: Review: Code needed, Review: QA needed

#201 2568 find a partner
  templates/partners/find-a-partner.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#200 Update desktop partners page, add strip and card variants
  static/sass/_pattern_cards.scss
  static/sass/_pattern_strip.scss
  templates/partners/desktop.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#203 Add redirect
  redirects.yaml
Labels: Review: Code +1, Review: QA +1

#204 Update flask-base to 0.5.1
  .circleci/config.yml
  .env
  requirements.txt
Labels: Review: Code +1, Review: QA +1

#206 Update /partners/cloud page
  templates/partners/cloud.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#208 Update become a partner page
  templates/partners/become-a-partner.html
  templates/partners/thank-you.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#205 Render job application questions from api response
  templates/careers/job-detail.html
  webapp/greenhouse.py
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#213 Check department is not Null before parsing it
  webapp/greenhouse.py
Labels: Review: Code +1, Review: QA +1

#209 Add channel-and-reseller page
  package.json
  static/sass/_pattern_strip.scss
  templates/partners/channel-and-reseller.html
  templates/partners/cloud.html
  yarn.lock
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#210 Add IHV and OEM partners page
  templates/partners/ihv-and-oem.html
  tests/test_routes.py
  webapp/app.py
  webapp/partners.py
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#211 Update to focal
  Dockerfile
  requirements.txt
Labels: Review: Code +1, Review: QA +1

#215 Add secondary nav for /partners
  redirects.yaml
  templates/base_index.html
  templates/partial/_navigation-partners.html
  templates/partial/_navigation.html
  templates/partial/_partners-footer.html
  templates/partners/cloud.html
  templates/partners/desktop.html
Labels: Review: Code +1, Review: QA +1

#216 Add system-integrators partners page
  templates/partners/system-integrators.html
  webapp/app.py
  webapp/partners.py
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#218 Remove unused send cv template
  templates/partial/_careers-send-cv.html
Labels: Review: Code +1, Review: QA +1
