Repository canonical/canonical.com, pull requests merged in 2021-12, with the labels that each got.

#453 Build iot device page on /partners/iot-device
  templates/partners/iot-device.html
  webapp/app.py
  webapp/partners.py
Labels: Review: Code +1, Review: QA +1, Review: Design +1

#451 Add iot-device page on /partners
  templates/partners/_secondary-navigation.html
  templates/partners/index.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#449 Add warning message if CV size is over 1MB
  static/js/file-validation.js
Labels: Review: Code +1, Review: QA +1

#457 Enable image template tag to work on canonical.com
  requirements.txt
  webapp/app.py
Labels: Review: Code +1, Review: QA +1

#455 Fix the responsiveness of the filter on /careers/all
  static/sass/_pattern_forms.scss
  static/sass/_pattern_lists.scss
  templates/partial/_careers-navigation.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1, Review: Design +1

#458 Fix ethics typo
  templates/careers/ethics.html
Labels: Review: Code +1

#459 Fix github dotrun action
  .github/workflows/pr.yaml
Labels: Review: Code +1, Review: QA +1
