Repository canonical/canonical.com, pull requests merged in 2021-11, with the labels that each got.

#443 Add redirect from '/landscape/dedicated-edition' to 'ubuntu.com/support'
  redirects.yaml
Labels: Review: Code +1, Review: QA +1

#442 Career game mobile fix
  .gitignore
  static/sass/_pattern_cards.scss
  static/sass/_pattern_footer.scss
  templates/careers/start.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#450 Create github issue template for canonical.com
  .github/ISSUE_TEMPLATE/ISSUE_TEMPLATE.md
Labels: Review: QA +1, Review: Code +1 (with changes)
