Repository canonical/canonical.com, pull requests merged in 2022-08, with the labels that each got.

#597 Add extra footer link only to careers pages
  static/sass/_pattern_footer.scss
  templates/partial/_footer.html
Labels: Review: Code +1, Review: QA +1

#589 Simplify the navigation across the site
  static/sass/_pattern_navigation.scss
  templates/base_index.html
  templates/partial/_navigation.html
  templates/partial/navigation-careers.html
  templates/partial/navigation-partners.html
  templates/partial/navigation-products.html
Labels: Review: QA +1, Review: UX +1, Review: Code +1 (with changes)

#607 check "vacancies" is present in the context
  webapp/app.py
Labels: Review: Code +1, Review: QA +1

#609 update job postings to allow video embeds
  templates/careers/job-detail.html
  webapp/app.py
Labels: Review: Code +1, Review: QA +1

#593 Send withdrawal confirmation email
  konf/site.yaml
  templates/applications/application.html
  templates/careers/application/_activate-email.html
  templates/careers/application/_interview-card.html
  templates/careers/application/_withdrawal-form.html
  templates/careers/application/index.html
  templates/careers/application/withdrawal-requested.html
  templates/careers/application/withdrawal.html
  webapp/application.py
  webapp/greenhouse.py
  webapp/utils/cipher.py
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#602 Update process section
  package.json
  static/sass/_pattern_application.scss
  static/sass/styles.scss
  templates/careers/application/_interview-card-done.html
  templates/careers/application/_interview-card.html
  templates/careers/application/index.html
  webapp/application.py
  webapp/hiring_leads.json
  yarn.lock
Labels: Review: QA +1, Review: UX +1, Review: Design +1, Review: Code +1 (with changes)
