Repository canonical/canonical.com, pull requests merged in 2022-05, with the labels that each got.

#540 Update /careers job view for canonical-v3
  static/js/tabs.js
  static/sass/_pattern_cards.scss
  static/sass/_pattern_lists.scss
  static/sass/_settings.scss
  static/sass/styles.scss
  templates/careers/_filters.html
  templates/careers/base-tabs.html
  templates/careers/base-template.html
  templates/careers/results.html
  templates/partial/_careers-available-roles.html
  templates/partial/_careers-navigation.html
  templates/practice/documentation.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#535 Refresh /partners/become-a-partner for canonical-v3
  templates/partial/_partners-footer.html
  templates/partners/become-a-partner.html
Labels: Review: Code +1, Review: QA +1

#538 Refresh /careers for canonical-v3
  static/sass/_pattern_lists.scss
  static/sass/_utilities_accent-border.scss
  static/sass/styles.scss
  templates/careers/index.html
  templates/partners/desktop.html
  templates/partners/ihv-and-oem.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#534 Refresh /partners/public-cloud for canonical-v3
  templates/partners/public-cloud.html
Labels: Review: Code +1, Review: QA +1

#541 Create /working-here page
  static/sass/_pattern_cards.scss
  static/sass/_utilities_accent-border.scss
  templates/careers/working-here.html
  templates/partners/desktop.html
  templates/partners/ihv-and-oem.html
Labels: Review: Code +1, Review: QA +1

#548 Update homepage logo and footer copyright year
  templates/index.html
Labels: Review: Code +1, Review: QA +1

#549 add links to privacy notices on application forms
  templates/careers/job-detail.html
Labels: Review: Code +1, Review: QA +1

#547 Display user error on empty results
  templates/careers/results.html
  webapp/app.py
Labels: Review: Code +1, Review: QA +1

#542 Update with design suggestions
  static/sass/_pattern_cards.scss
  templates/careers/apply.html
  templates/partners/become-a-partner.html
  templates/partners/channel-and-reseller.html
  templates/partners/desktop.html
  templates/partners/find-a-partner.html
  templates/partners/gsi.html
  templates/partners/ihv-and-oem.html
  templates/partners/iot-device.html
  templates/partners/public-cloud.html
Labels: Review: Design +1

#551 Build /company page
  redirects.yaml
  templates/company/index.html
  templates/partial/_navigation-company.html
  templates/partial/_navigation.html
Labels: Review: Code +1, Review: QA +1, Review: Design +1

#552 Demo: homepage
  static/sass/_pattern_cards.scss
  static/sass/_pattern_tabs.scss
  static/sass/styles.scss
  templates/index.html
Labels: Review: Code +1, Review: QA +1

#545 Update /products search view to canonical-v3
  products.json
  static/js/products-tabs.js
  templates/careers/all.html
  templates/careers/apply.html
  templates/careers/diversity/index.html
  templates/careers/ethics.html
  templates/careers/lifestyle.html
  templates/careers/progression.html
  templates/careers/travel.html
  templates/partial/_navigation-careers.html
  templates/partial/_navigation-products.html
  templates/partial/_navigation.html
  templates/products/_product-cards.html
  templates/products/_product-navigation.html
  templates/products/_products-search.html
  templates/products/index.html
  webapp/app.py
Labels: Review: Design needed, Review: Code +1, Review: QA +1
