Repository canonical/canonical.com, pull requests merged in 2022-04, with the labels that each got.

#510 Add ISV partners page
  templates/partners/isv-partners.html
Labels: Review: Code +1, Review: QA +1, Review: Design +1

#515 Update become a partner form
  templates/partners/become-a-partner.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#502 Canonical press centre
  static/sass/_pattern_footer.scss
  static/sass/_pattern_strip.scss
  templates/blog/article.html
  templates/blog/newsletter-form.html
  templates/press-centre/card.html
  templates/press-centre/index.html
  webapp/app.py
Labels: Review: QA +1, Review: Design +1, Review: Code +1 (with changes)

#516 Update copy on /partners/isv-partners
  templates/partners/isv-partners.html
Labels: Review: Code +1, Review: QA +1

#517 Update /project/directory
  templates/projects/directory.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#519 Update the address of Taipei Office
  templates/contact-us.html
Labels: Review: Code +1, Review: QA +1

#524 Update the contract for the Vanilla framework project
  templates/projects/directory.html
Labels: Review: Code +1

#527 Update /partners/desktop for canonical-v3
  static/sass/_pattern_cards.scss
  templates/partners/desktop.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#525 Fix side nav z-index
  templates/practice/documentation.html
Labels: Review: Code +1, Review: QA +1

#529 Add isv partners page to partners subnav
  templates/partners/_secondary-navigation.html
  templates/partners/isv-partners.html
Labels: Review: Code +1, Review: QA +1

#537 Update practices documentation
  templates/practice/documentation.html
Labels: Review: Code +1, Review: QA +1

#536 Refresh /partners/find-a-partner for canonical-v3
  templates/partners/find-a-partner.html
Labels: Review: Code +1, Review: QA +1

#533 Refresh /partners/gsi for canonical-v3
  templates/partners/gsi.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#539 Update documentation careers page
  templates/practice/documentation.html
Labels: Review: Code +1, Review: QA +1
