Repository canonical/canonical.com, pull requests merged in 2022-03, with the labels that each got.

#495 Remove "department" field from Greenhouse lookup
  webapp/greenhouse.py
Labels: Review: Code +1, Review: QA +1

#496 Create "canonical" dropdown navigation item
  static/js/navigation.js
  static/sass/_pattern_navigation.scss
  templates/partial/_navigation.html
  templates/partial/navigation-canonical.html
  templates/partial/navigation-careers.html
  templates/partial/navigation-partners.html
  templates/partial/navigation-products.html
  templates/partners/_secondary-navigation.html
  tests/test_routes.py
  webapp/app.py
  webapp/views.py
Labels: Review: Code needed, Review: QA needed, Review: UX +1

#499 Add search bar and search page
  .stylelintrc
  konf/site.yaml
  package.json
  requirements.txt
  run
  static/sass/_pattern_buttons.scss
  static/sass/_pattern_cards.scss
  static/sass/_pattern_careers-modal.scss
  static/sass/_pattern_footer.scss
  static/sass/_pattern_forms.scss
  static/sass/_pattern_headings.scss
  static/sass/_pattern_lists.scss
  static/sass/_pattern_media-object.scss
  static/sass/_pattern_navigation.scss
  static/sass/_pattern_strip.scss
  static/sass/styles.scss
  templates/partial/_navigation.html
  templates/search.html
  tests/test_routes.py
  webapp/app.py
  yarn.lock
Labels: Review: QA +1, Review: Code +1 (with changes)

#504 Update flask-base to the latest 1.0.2
  requirements.txt
Labels: Review: Code +1, Review: QA +1

#498 Canonical blog
  requirements.txt
  static/sass/_pattern_blog-card.scss
  static/sass/_pattern_strip.scss
  static/sass/styles.scss
  templates/base_index.html
  templates/blog/archives.html
  templates/blog/article.html
  templates/blog/author.html
  templates/blog/blog-card-header.html
  templates/blog/blog-card.html
  templates/blog/featured-articles.html
  templates/blog/filters.html
  templates/blog/index.html
  templates/blog/newsletter-form.html
  templates/blog/singular-category.html
  templates/blog/tag.html
  templates/blog/topic.html
  templates/shared/_pagination.html
  webapp/app.py
Labels: Review: Code +1, Review: QA +1, Review: UX +1, Review: Design +1, Review: A11y +1

#506 Create thank-you page
  templates/careers/thank-you.html
  webapp/app.py
Labels: Review: Code +1, Review: QA +1, Review: PdM +1

#513 Update lxd link
  templates/index.html
  templates/partial/navigation-products.html
Labels: Review: Code +1, Review: QA +1
