Repository canonical/canonical.com, pull requests merged in 2022-09, with the labels that each got.

#616 Implement design modal
  static/sass/_pattern_application.scss
  static/sass/styles.scss
  templates/careers/application/_withdrawal-form.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1 (with changes)

#619 Build faq page
  static/sass/_pattern_application.scss
  templates/careers/application/faq.html
  webapp/application.py
Labels: Review: Code +1, Review: QA +1, Review: Design +1, Review: A11y +1

#621 Divide code in `careers/application/index.html` into different files
  templates/careers/application/index.html
  templates/careers/application/partial/_assessment.html
  templates/careers/application/partial/_early-stage.html
  templates/careers/application/partial/_late-stage.html
  templates/careers/application/partial/_lifestyle.html
  webapp/application.py
Labels: Review: Code +1, Review: QA +1

#622 Send rejection confirmation email
  webapp/greenhouse.py
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#626 Application page token format
  webapp/application.py
  webapp/hiring_leads.json
Labels: Review: Code +1, Review: QA +1

#628 Fix missing scheduled interviews
  templates/careers/application/partial/_assessment.html
  templates/careers/application/partial/_early-stage.html
  templates/careers/application/partial/_late-stage.html
  webapp/application.py
  webapp/greenhouse.py
  webapp/hiring_leads.json
Labels: Review: Code +1, Review: QA +1

#629 Fix missing candidate object on application page
  webapp/application.py
Labels: Review: Code +1, Review: QA +1

#625 Update view after rejection
  templates/careers/application/index.html
  webapp/application.py
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#605 /careers and /careers/all redesign
  static/js/careers-filter-and-sort.js
  static/sass/_pattern_forms.scss
  static/sass/_pattern_search-form.scss
  static/sass/_pattern_search-panel.scss
  static/sass/styles.scss
  templates/base_index.html
  templates/careers/_careers-pagination.html
  templates/careers/_search.html
  templates/careers/all.html
  templates/careers/base.html
  templates/careers/index.html
  templates/partial/_careers-available-roles.html
  templates/partial/_careers-navigation.html
  webapp/app.py
Labels: Review: Code +1, Review: QA +1, Review: UX +1, Review: Design +1

#634 Add meta tag to hide documentation page from search engines
  templates/practice/documentation.html
Labels: Review: Code +1, Review: QA +1

#637 Remove buttons for pending pages
  templates/careers/index.html
Labels: Review: Code +1, Review: QA +1
