Repository canonical/canonical.com, pull requests merged in 2022-11, with the labels that each got.

#654 Improve layout of candidate page
  static/sass/_pattern_application.scss
  static/sass/styles.scss
  templates/careers/all.html
  templates/careers/application/_interview-card-done.html
  templates/careers/application/index.html
  templates/careers/application/partial/_early-stage.html
  templates/careers/base.html
  templates/partial/_careers-available-roles.html
  templates/partial/_careers-navigation.html
  webapp/application.py
  webapp/hiring_leads.json
Labels: Review: Code +1, Review: QA +1, Review: UX +1, Review: Design +1

#683 Fix the stepper styling
  static/sass/_pattern_application.scss
Labels: Review: Code +1, Review: QA +1

#687 Remove the behavioural traits part from the Psychometric assessment s…
  templates/careers/application/partial/_assessment.html
Labels: Review: Code +1

#690 Fix show all functionality
  static/js/careers-filter-and-sort.js
Labels: Review: Code +1, Review: QA +1

#685 Hiring leads meeting feedback
  static/sass/_pattern_application.scss
  templates/careers/application/index.html
  webapp/hiring_leads.json
Labels: Review: Code +1, Review: QA +1

#686 Render job post title instead of job title in application page
  templates/careers/application/index.html
  webapp/application.py
  webapp/greenhouse.py
Labels: Review: Code +1, Review: QA +1

#691 Remove the offer stage from the application view
  templates/careers/application/index.html
Labels: Review: Code +1, Review: QA +1

#684 Add Ga tracking to navigation
  static/js/navigation.js
  templates/partial/_navigation.html
Labels: Review: Code +1, Review: QA +1

#692 Add Simon Aronsson to the hiring leads bios
  webapp/hiring_leads.json
Labels: Review: Code +1

#699 Allow job post id to be null
  templates/careers/application/index.html
  webapp/application.py
Labels: Review: Code +1, Review: QA +1

#695 Fix become a partner submission form
  templates/partners/become-a-partner.html
Labels: Review: Code +1, Review: QA +1

#702 Fix mobile homepage
  templates/index.html
  tests/cypress/integration/sample_spec.js
Labels: Review: Code +1, Review: QA +1

#703 Fix 'products' navigation link
  static/js/navigation.js
  templates/partial/_navigation.html
Labels: Review: Code +1, Review: QA +1

#697 Apply redesign and re-order departments
  static/js/careers-filter-and-sort.js
  static/sass/_pattern_search-form.scss
  templates/careers/_search.html
  templates/careers/all.html
  templates/careers/base.html
  templates/partial/_careers-available-roles.html
  templates/partial/_careers-navigation.html
  webapp/app.py
Labels: Review: Code +1, Review: QA +1, Review: Design +1

#706 Remove the all roles from the department pages
  redirects.yaml
  static/js/careers-filter-and-sort.js
  templates/careers/admin.html
  templates/careers/base-tabs.html
  templates/careers/departments.html
  templates/careers/engineering.html
  templates/careers/finance.html
  templates/careers/human-resources.html
  templates/careers/index.html
  templates/careers/legal.html
  templates/careers/marketing.html
  templates/careers/operations.html
  templates/careers/project-management.html
  templates/careers/sales.html
  templates/careers/support-engineering.html
  templates/careers/web-and-design.html
  webapp/app.py
Labels: Review: Code +1, Review: QA +1
