Repository canonical/canonical.com, pull requests merged in 2022-10, with the labels that each got.

#639 Allow href attribute on links in job descriptions
  webapp/app.py
Labels: Review: Code +1, Review: QA +1

#632 Departments overview build
  templates/careers/career-explorer.html
  templates/careers/departments.html
  templates/careers/results.html
  templates/careers/sitemap.xml
Labels: Review: Code +1, Review: QA +1, Review: UX +1, Review: Design +1

#643 change theme-color to Canonical's accent color
  templates/base_index.html
Labels: Review: Code +1, Review: QA +1

#651 Update copy & include video on /application
  templates/careers/application/index.html
  templates/careers/application/partial/_assessment.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#652 Fix access to the hired view on application page
  webapp/application.py
Labels: Review: QA needed, Review: Code +1

#656 Update the company address across the site
  templates/contact-us.html
Labels: Review: Code +1, hacktoberfest-accepted

#658 Fix the /career/start path
  webapp/app.py
Labels: Review: Code +1, Review: QA +1

#662 update link on careers index
  templates/careers/index.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#666 Map the career locations filter to the supported regions
  static/js/careers-filter-and-sort.js
  templates/careers/_filters.html
  templates/partial/_careers-navigation.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1, Review: PdM +1

#667 Fix secondary nav bug
  static/sass/_pattern_navigation.scss
Labels: Review: Code +1, Review: QA +1

#668 Pass the gh_src URL param to the application
  static/js/source-inheritance.js
  templates/base_index.html
  templates/careers/base_job-details.html
  templates/careers/job-detail.html
Labels: Review: Code +1, Review: QA +1

#664 Update hiring leads bio
  webapp/hiring_leads.json
Labels: Review: Code +1

#650 Update navigation to new vanilla pattern with new items
  static/js/navigation.js
  static/sass/styles.scss
  templates/base_index.html
  templates/index.html
  templates/partial/_navigation.html
  templates/partners/channel-and-reseller.html
  templates/partners/find-a-partner.html
  templates/partners/ihv-and-oem.html
  templates/partners/public-cloud.html
Labels: Review: Code +1, Review: QA +1, Review: Design +1

#672 improve Google JobPosting
  templates/careers/job-detail.html
  webapp/application.py
  webapp/job_regions.py
Labels: Review: Code +1, Review: QA +1

#676 fix products link
  templates/partial/_navigation.html
Labels: Review: Code +1, Review: QA +1

#677 update nav banner
  templates/partial/_navigation.html
Labels: Review: Code needed, Review: QA needed
