Repository canonical/canonical.com, pull requests merged in 2022-12, with the labels that each got.

#704 Get the current milestone based on the historical list of stages
  tests/test_application.py
  webapp/application.py
Labels: Review: Code +1, Review: QA +1

#712 fix the case where there are multiple hold stages
  webapp/application.py
Labels: Review: Code +1, Review: QA +1

#717 Remove get_partner_groups from homepage view
  webapp/app.py
  webapp/partners.py
Labels: Review: Code +1, Review: QA +1

#711 Remove filters from pages no longer tied to all roles
  templates/careers/diversity/identity.html
  templates/careers/diversity/index.html
  templates/careers/ethics.html
  templates/careers/lifestyle.html
  templates/careers/progression.html
  templates/careers/travel.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#718 fix products nav issue
  templates/partial/_navigation.html
Labels: Review: Code +1, Review: QA +1

#719 add missing month_name context method
  webapp/app.py
Labels: Review: Code +1, Review: QA +1

#723 Fix departments to handle new response format from API
  .github/workflows/pr.yaml
  webapp/greenhouse.py
Labels: Review: Code needed, Review: QA needed

#725 Update search search bar and remove /careers/departments
  redirects.yaml
  static/sass/_pattern_search-form.scss
  templates/careers/all.html
  templates/careers/departments.html
Labels: Review: Code +1, Review: QA +1

#721 Update the Hiring lead bios
  webapp/hiring_leads.json
Labels: Review: Code +1

#701 Update department pages and add latest news
  package.json
  static/sass/_pattern_blog-card.scss
  static/sass/styles.scss
  templates/careers/admin.html
  templates/careers/administration.html
  templates/careers/all.html
  templates/careers/engineering.html
  templates/careers/finance.html
  templates/careers/human-resources.html
  templates/careers/index.html
  templates/careers/legal.html
  templates/careers/marketing.html
  templates/careers/operations.html
  templates/careers/people.html
  templates/careers/project-management.html
  templates/careers/sales.html
  templates/careers/support-engineering.html
  templates/careers/web-and-design.html
  templates/shared/_blog-card.html
  templates/shared/_fast_track_jobs.html
  templates/shared/_featured_jobs.html
  templates/shared/_social-icons-section-with-github-extended.html
  templates/shared/_social-icons-section-with-github.html
  templates/shared/_social-icons-section.html
  webapp/app.py
  webapp/greenhouse.py
Labels: Review: Code +1, Review: QA +1, Review: UX +1, Review: Design +1

#720 Add departments overview to /careers
  templates/careers/index.html
  webapp/app.py
Labels: Review: Code +1, Review: QA +1, Review: UX +1, Review: Design +1

#735 Fix when a job is not available in an application
  templates/careers/application/index.html
Labels: Review: Code +1, Review: QA +1

#738 Fix typo on engineering dept page
  templates/careers/engineering.html
Labels: Review: Code +1

#741 Hide application withdrawal
  templates/careers/application/index.html
Labels: Review: Code +1, Review: QA +1
