Repository canonical/canonical.com, pull requests merged in 2023-01, with the labels that each got.

#739 Expand careers search to also search by skills
  templates/careers/_search.html
Labels: Review: Code +1, Review: QA +1

#737 Check the HL image exists before rendering an img
  templates/careers/application/index.html
Labels: Review: Code +1, Review: QA +1

#748 WD-1142 Remove Working at Canonical from the menu
  templates/partial/_navigation.html
Labels: Review: UX needed, Review: Code +1, Review: QA +1

#751 WD-1163: Fix number of roles in /careers/all
  static/js/careers-filter-and-sort.js
  templates/careers/_search.html
  tests/test_greenhouse.py
  webapp/app.py
  webapp/greenhouse.py
Labels: Review: Code +1, Review: QA +1

#753 Add cachebusting version strings to all /static/js files
  templates/base_index.html
  templates/careers/_vacancies-modal.html
  templates/careers/apply.html
  templates/careers/career-explorer.html
  templates/partners/find-a-partner.html
Labels: Review: Code +1, Review: QA +1

#754 Fix featured and fast-track jobs
  .gitignore
  package.json
  tests/cassettes/TestRoutes.test_invalid_careers_department.yaml
  tests/test_routes.py
  webapp/app.py
Labels: Review: Code +1, Review: QA +1

#756 Show 401 error page when /careers/application token missing or wrong
  templates/401.html
  webapp/app.py
  webapp/application.py
  webapp/utils/cipher.py
Labels: Review: Code +1, Review: QA +1

#758 Remove broken link from /practice/documentation
  templates/practice/documentation.html
Labels: Review: Code needed, Review: QA needed

#762 Update URL on input clear
  static/js/careers-filter-and-sort.js
  templates/careers/_search.html
Labels: Review: Code +1, Review: QA +1

#761 WD-1449 Improve the link to the JD from the candidates page
  templates/careers/application/index.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#759 Split role description and application form
  static/sass/styles.scss
  templates/careers/base_job-details.html
  templates/careers/job-detail.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1, Review: Design +1

#772 Add req id to job content
  webapp/greenhouse.py
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#763 Update footer format
  static/sass/_pattern_footer.scss
  static/sass/styles.scss
  templates/partial/_footer.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1, Review: Design +1

#773 WD-1787 Updates to the application FAQ content
  templates/careers/application/faq.html
Labels: Review: Code +1, Review: UX +1
