Repository canonical/canonical.com, pull requests merged in 2023-12, with the labels that each got.

#1124 Add postgresql page to data bubble and subnav
  templates/data/postgresql.html
  templates/data/spark.html
  templates/partial/_data-navigation.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1, Review: Design +1

#1135 Update time to complete the WI in the FAQ
  templates/careers/application/faq.html
Labels: Review: Code +1

#1127 WD-7565 LXD install page
  templates/data/mysql.html
  templates/lxd/_form-lxd-install.html
  templates/lxd/install.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1, Review: Design +1

#1139 WD-7611 - add diversity button on application
  templates/careers/application/index.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#1142 WD-5190 - fix PM subheading
  templates/careers/project-management.html
Labels: Review: Code +1, Review: QA +1

#1136 WD-7312 - open privacy policy in a new tab on careers
  templates/blog/article.html
  templates/blog/newsletter-form.html
  templates/careers/application/_activate-email.html
  templates/careers/job-detail.html
  templates/contact-us.html
  templates/data/_data-form.html
  templates/data/_form-data-kafka.html
  templates/data/_form-data-mongodb.html
  templates/data/_form-data-opensearch.html
  templates/data/_form-data-relational-dbs.html
  templates/data/_form-data-spark.html
  templates/microcloud/_microcloud-modal.html
  templates/microcloud/contact-us.html
  templates/partial/_footer.html
  templates/partners/become-a-partner.html
  templates/partners/partial/_executive-summit-form.html
  templates/partners/partial/_homepage-form.html
Labels: Review: Code +1, Review: QA +1

#1138 LXD bubble feature branch
  static/sass/_pattern_strip.scss
  static/sass/styles.scss
  templates/data/mysql.html
  templates/lxd/_form-lxd-install.html
  templates/lxd/index.html
  templates/lxd/install.html
  templates/lxd/manage.html
  templates/partial/_lxd-navigation.html
  templates/partial/_navigation.html
Labels: Review: QA +1

#1140 Build /solutions/big-data-ai and modal
  templates/solutions/_form-big-data-ai.html
  templates/solutions/big-data-ai.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1, Review: Design +1

#1147 WD-7949 - Tweak Data Fabric pages
  templates/data/index.html
  templates/data/mysql.html
  templates/partial/_data-navigation.html
Labels: Review: Code +1, Review: QA +1

#1145 Update LXD logo
  templates/partial/_lxd-navigation.html
Labels: Review: Code +1, Review: QA +1

#1137 Update isometric images
  templates/data/mysql.html
Labels: Review: Code +1, Review: QA +1

#1128 Fix navigation by checking for .p-modal before toggling
  templates/careers/application/index.html
Labels: Review: Code +1, Review: QA +1

#1148 Fix the title of careers pages
  templates/careers/job-detail.html
  webapp/greenhouse.py
Labels: Review: Code +1, Review: QA +1

#1146 WD-5607 - Update the projects directory
  templates/projects/directory.html
Labels: Review: Code +1, Review: QA +1
