Repository canonical/canonical.com, pull requests merged in 2023-09, with the labels that each got.

#1031 [copy update] /partners/silicon
  templates/partners/silicon.html
Labels: Review: Code +1, Review: QA +1

#1035 WD-5751 - Add redirect for /enterprise-services
  redirects.yaml
Labels: Review: Code +1, Review: QA +1

#1040 WD-6068 Fix navigation on application page
  templates/careers/application/_withdrawal-form.html
  templates/careers/application/index.html
Labels: Review: Code +1, Review: QA +1

#1034 WD-6197 - Update the canonical URL for articles authored by Canonical
  templates/blog/article.html
Labels: Review: Code +1, Review: QA +1

#1039 Add modal form for Canonical /contact-us
  templates/contact-us.html
  templates/index.html
  templates/partners/partial/_homepage-form.html
Labels: Review: Code needed, Review: QA needed, Review: UX +1

#1041 Revert "WD-6068 Fix navigation on application page"
  templates/careers/application/_withdrawal-form.html
  templates/careers/application/index.html
Labels: Review: Code +1

#1042 Update _homepage-form.html
  templates/partners/partial/_homepage-form.html
  templates/shared/forms/_country.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#1055 Null check the UTM search field
  templates/base_index.html
Labels: Review: Code +1, Review: QA +1

#1057 Remove travel locations from the FAQ
  templates/careers/application/faq.html
Labels: Review: Code +1

#1043 Build new /data page
  static/sass/_pattern_strip.scss
  static/sass/styles.scss
  templates/data/_data-form.html
  templates/data/index.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1, Review: Design +1

#1044 Build /data/spark
  static/sass/styles.scss
  templates/data/_form-data-spark.html
  templates/data/spark.html
  templates/index.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1, Review: Design +1

#1059 Fix capitalisation of united in address
  templates/contact-us.html
Labels: Review: Code +1
