Repository canonical/canonical.com, pull requests merged in 2023-05, with the labels that each got.

#836 Update navigation to use latest vanilla pattern
  static/sass/_pattern_navigation.scss
  static/sass/styles.scss
  templates/partial/_navigation.html
Labels: Review: Code +1, Review: Design +1

#851 Advantage->Pro
  templates/projects/index.html
Labels: Review: Code +1, Review: QA +1

#853 Update login position on /partners
  static/sass/styles.scss
  templates/partial/_partners-footer.html
  templates/partners/index.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1, Review: Design +1

#854 Update to vanilla-4.0-alpha
  package.json
  static/sass/_pattern_blog-card.scss
  static/sass/_pattern_careers-progression.scss
  yarn.lock
Labels: Review: QA +1

#857 Revert "Get hiring leads bio"
  konf/site.yaml
  requirements.txt
  templates/careers/application/index.html
  tests/cassettes/TestApplicationPageHelpers.test_get_employee_directory_data.yaml
  tests/test_application.py
  webapp/app.py
  webapp/application.py
  webapp/hiring_leads.json
Labels: Review: Code +1, Review: QA +1

#850 on candidate withdrawal send email to hiring lead - WD-2917
  templates/careers/application/_withdrawal_notification-email.html
  templates/careers/application/withdrawal.html
  webapp/application.py
Labels: Review: Code +1, Review: QA +1

#863 🤓 [homepage] featured products header alignment
  static/sass/styles.scss
  templates/index.html
  webapp/app.py
  webapp/static_data.py
Labels: Review: Code +1, Review: QA +1

#866 WD-3653 Add Q and A for written interview feedback
  templates/careers/application/faq.html
Labels: Review: Code +1, Review: QA +1

#859 Add GIA candidate feedback download link to Candidate page
  static/js/applications/get-report.js
  static/sass/_pattern_application.scss
  static/sass/_pattern_careers-modal.scss
  static/sass/styles.scss
  templates/careers/application/_interview-card-done.html
  templates/careers/application/_withdrawal-form.html
  templates/careers/application/index.html
  templates/careers/application/partial/_assessment.html
  tests/test_application.py
  webapp/application.py
Labels: Review: QA +1, Review: UX +1, Review: Code +1 (with changes)

#868 Update the candidate feedback reports on FAQ
  templates/careers/application/faq.html
Labels: Review: Code +1, Review: QA +1

#869 WD-3415 Design consistency for blockquote pattern
  templates/careers/company-culture.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#858 WD-1154 Get hiring leads bio
  konf/site.yaml
  requirements.txt
  templates/careers/application/index.html
  tests/cassettes/TestApplicationPageHelpers.test_get_employee_directory_data.yaml
  tests/test_application.py
  webapp/app.py
  webapp/application.py
  webapp/hiring_leads.json
Labels: Review: Code +1, Review: QA +1

#873 Revert "WD-1154 Get hiring leads bio"
  konf/site.yaml
  requirements.txt
  templates/careers/application/index.html
  tests/cassettes/TestApplicationPageHelpers.test_get_employee_directory_data.yaml
  tests/test_application.py
  webapp/app.py
  webapp/application.py
  webapp/hiring_leads.json
Labels: Review: QA +1
