Repository canonical/canonical.com, pull requests merged in 2023-04, with the labels that each got.

#830 WD-2904 Add Kathy Pelich bio and updates a few large images
  webapp/hiring_leads.json
Labels: Review: Code +1, Review: QA +1

#809 Build sustainability page
  package.json
  static/sass/styles.scss
  templates/careers/administration.html
  templates/careers/commercial-operations.html
  templates/careers/engineering.html
  templates/careers/finance.html
  templates/careers/legal.html
  templates/careers/marketing.html
  templates/careers/people.html
  templates/careers/product.html
  templates/careers/project-management.html
  templates/careers/sales.html
  templates/careers/support-engineering.html
  templates/careers/sustainability.html
  templates/careers/travel.html
  tests/test_routes.py
  webapp/app.py
  yarn.lock
Labels: Review: Code +1, Review: QA +1, Review: UX +1, Review: Design +1

#823 WD-2175 Career progression
  package.json
  static/js/careers-progression.js
  static/sass/_pattern_careers-progression.scss
  static/sass/styles.scss
  templates/careers/_careers-progression-slides.html
  templates/careers/_search.html
  templates/careers/base-tabs.html
  templates/careers/base.html
  templates/careers/progression.html
  templates/partial/_navigation.html
  tests/cassettes/TestRoutes.test_careers_progression.yaml
  tests/test_routes.py
  webapp/app.py
  yarn.lock
Labels: Review: QA +1, Review: UX +1, Review: Design +1, Review: Code +1 (with changes)

#832 Build culture page
  static/sass/styles.scss
  templates/careers/company-culture.html
  templates/partial/_navigation.html
  tests/test_routes.py
  webapp/app.py
Labels: Review: Code +1, Review: QA +1, Review: UX +1, Review: Design +1

#837 WD-2082 Add analytics to fast track and featured roles
  templates/shared/_fast_track_jobs.html
  templates/shared/_featured_jobs.html
Labels: Review: Code +1, Review: QA +1

#845 Fixing "recruitment" typo
  templates/partial/_footer.html
Labels: Review: Code +1

#847 Fix grid in "We're Canonical" section
  templates/careers/company-culture.html
Labels: Review: Code needed, Review: QA needed

#839 /partners redesign
  static/sass/_pattern_footer.scss
  static/sass/_pattern_strip.scss
  static/sass/styles.scss
  templates/partial/_partners-footer.html
  templates/partners/index.html
Labels: Review: Design needed, Review: Code +1, Review: QA +1

#840 Build diversity page
  redirects.yaml
  static/sass/styles.scss
  templates/careers/company-culture/diversity.html
  templates/careers/diversity/identity.html
  templates/careers/diversity/index.html
  templates/partial/_navigation.html
  tests/test_routes.py
Labels: Review: Code +1, Review: QA +1, Review: UX +1, Review: Design +1
