Repository canonical/canonical.com, pull requests merged in 2023-10, with the labels that each got.

#1046 Build /data/mongodb
  static/sass/styles.scss
  templates/data/_form-data-mongodb.html
  templates/data/mongodb.html
Labels: Review: QA +1, Review: UX +1, Review: Design +1, Review: Code +1 (with changes), Review: PdM +1

#1045 Build /data/opensearch
  templates/data/_form-data-opensearch.html
  templates/data/opensearch.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1, Review: Design +1

#1058 WD-5874 - Build the /data/kafka page and modal form
  static/sass/_pattern_careers-modal.scss
  templates/data/_form-data-kafka.html
  templates/data/kafka.html
Labels: Review: QA +1, Review: UX +1, Review: Design +1, Review: Code +1 (with changes), Review: A11y +1

#1068 WD-6621 - update /company-culture page
  templates/careers/company-culture/index.html
Labels: Review: QA +1

#1072 [copy update] /data/mongodb
  templates/data/mongodb.html
Labels: Review: Code +1, Review: QA +1

#1066 Build data relational databases page
  templates/data/_form-data-relational-dbs.html
  templates/data/relational-databases.html
  templates/data/spark.html
Labels: Review: UX needed, Review: QA +1, Review: Design +1, Review: Code +1 (with changes)

#1075 WD-6781 - Respect candidates with multiple email addresses when checking report
  tests/test_application.py
  webapp/application.py
Labels: Review: Code +1, Review: QA +1

#1056 Data bubble navigation
  .stylelintrc
  package.json
  static/sass/_pattern_global-nav.scss
  static/sass/styles.scss
  templates/data/_form-data-kafka.html
  templates/data/_form-data-opensearch.html
  templates/data/index.html
  templates/partial/_data-navigation.html
  templates/partial/_navigation.html
  templates/partial/_standard-navigation.html
  yarn.lock
Labels: Review: Code +1, Review: QA +1, Review: UX +1, Review: Design +1

#1067 Data bubble migration
  templates/index.html
Labels: Review: Code +1

#1082 Add data bubble to sitemaps
  templates/data/docs/mongodb/iaas/document.html
  templates/data/docs/mongodb/iaas/search-results.html
  templates/data/docs/mongodb/k8s/document.html
  templates/data/docs/mongodb/k8s/search-results.html
  templates/data/docs/mysql/iaas/document.html
  templates/data/docs/mysql/iaas/search-results.html
  templates/data/docs/mysql/k8s/document.html
  templates/data/docs/mysql/k8s/search-results.html
  templates/data/docs/opensearch/iaas/document.html
  templates/data/docs/opensearch/iaas/search-results.html
  templates/data/docs/postgresql/iaas/document.html
  templates/data/docs/postgresql/iaas/search-results.html
  templates/data/docs/postgresql/k8s/document.html
  templates/data/docs/postgresql/k8s/search-results.html
  templates/data/docs/spark/k8s/document.html
  templates/data/docs/spark/k8s/search-results.html
  templates/data/sitemap.xml
  templates/sitemap-links.xml
Labels: Review: Code +1

#1080 Fix/duplicated ids
  templates/partners/find-a-partner.html
  templates/partners/partial/_executive-summit-form.html
  templates/partners/partial/_homepage-form.html
Labels: Review: Code +1, Review: QA +1

#1087 make hero sections on data bubble more consistent
  static/sass/_pattern_strip.scss
  static/sass/styles.scss
  templates/data/index.html
  templates/data/kafka.html
  templates/data/mongodb.html
  templates/data/opensearch.html
  templates/data/spark.html
Labels: Review: Code +1, Review: QA +1

#1088 Bump canonicalwebteam.discourse to 5.4.3
  requirements.txt
Labels: Review: Code +1, Review: QA +1

#1089 Update Kubernetes logos
  templates/data/mongodb.html
  templates/data/opensearch.html
  templates/data/spark.html
Labels: Review: QA +1, Review: UX +1, Review: Code +1 (with changes)

#1092 Update application FAQ
  templates/careers/application/faq.html
Labels: Review: Code +1
