Repository canonical/canonical.com, pull requests merged in 2023-03, with the labels that each got.

#820 Remove location filters from explorer results
  templates/careers/base.html
Labels: Review: Code +1, Review: QA +1

#822 Show the Google Meet link for interviews today
  templates/careers/application/_interview-card.html
Labels: Review: Code +1, Review: QA +1

#815 Enable back withdraw application
  templates/careers/application/index.html
  webapp/application.py
Labels: Review: Code +1, Review: QA +1

#810 Rebuild travel and lifestyle page
  redirects.yaml
  static/js/sprint-map.js
  static/sass/styles.scss
  templates/careers/travel.html
  webapp/app.py
Labels: Review: QA +1, Review: UX +1, Review: Design +1, Review: Code +1 (with changes), Review: A11y +1

#794 WD-909 New career explorer
  .github/workflows/pr.yaml
  .gitignore
  build.js
  package.json
  static/js/career-explorer/App.tsx
  static/js/career-explorer/Explorer.tsx
  static/js/career-explorer/components/SelectableCard/SelectableCard.test.tsx
  static/js/career-explorer/components/SelectableCard/SelectableCard.tsx
  static/js/career-explorer/components/SelectableCards/SelectableCards.test.tsx
  static/js/career-explorer/components/SelectableCards/SelectableCards.tsx
  static/js/career-explorer/components/SelectedSkills/SelectedSkills.test.tsx
  static/js/career-explorer/components/SelectedSkills/SelectedSkills.tsx
  static/js/career-explorer/utils.ts
  static/js/careers-game.js
  static/js/types.ts
  static/sass/_pattern_cards.scss
  static/sass/_pattern_lists.scss
  static/sass/_pattern_search-panel.scss
  static/sass/styles.scss
  templates/careers/_skill.html
  templates/careers/_skills.html
  templates/careers/career-explorer.html
  templates/careers/results.html
  tsconfig.json
  yarn.lock
Labels: Review: QA +1, Review: UX +1, Review: Code +1 (with changes)

#828 Fix the department pages
  tests/cassettes/TestRoutes.test_department_page.yaml
  tests/test_routes.py
  webapp/app.py
Labels: Review: Code +1, Review: QA +1
