Repository canonical/canonical.com, pull requests merged in 2023-08, with the labels that each got.

#992 [copy update] WD-5286 update on footer privacy policy link
  templates/partial/_footer.html
Labels: Review: Code +1, Review: QA +1

#994 Limit newsletter to first page only
  templates/blog/index.html
Labels: Review: Code +1, Review: QA +1

#993 Fix footer
  templates/_error.tmpl
  templates/base_index.html
Labels: Review: Code +1, Review: QA +1

#1001 Update /careers/people copy
  templates/careers/people.html
Labels: Review: Code +1, Review: QA +1

#1000 Fix documentation typo
  templates/documentation/work-and-careers.html
Labels: Review: Code +1, Review: QA +1

#996 Fix homepage tabs on small screens
  package.json
  static/sass/_pattern_tabs.scss
  static/sass/styles.scss
  templates/index.html
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#989 WD-5371 - Remove the locate me input on applications
  static/js/apply-for-jobs.js
  templates/careers/job-detail.html
Labels: Review: Code +1, Review: QA +1

#999 Update quote
  templates/careers/company-culture/index.html
Labels: Review: Code needed, Review: QA needed

#1002 [copy update] WD-5487 Update copy doc links on 4 pages
  templates/partners/find-a-partner.html
  templates/partners/index.html
  templates/press-centre/index.html
  templates/projects/directory.html
Labels: Review: Code +1, Review: QA +1

#1006 Update sitemaps
  templates/careers/sitemap.xml
  templates/sitemap-index.xml
  templates/sitemap-links.xml
  webapp/app.py
Labels: Review: Code +1, Review: QA +1

#1007 Restore blogs tag page
  webapp/app.py
Labels: Review: Code +1, Review: QA +1

#1008 Refactor career base templates and remove stale templates
  templates/careers/_secondary-navigation.html
  templates/careers/base-tabs.html
  templates/careers/base-template.html
  templates/careers/base.html
  templates/careers/company-culture/diversity.html
  templates/careers/company-culture/index.html
  templates/careers/company-culture/progression.html
  templates/partners/_secondary-navigation.html
  webapp/app.py
Labels: Review: Code +1, Review: QA +1

#1010 Add missing tests
  tests/cassettes/TestRoutes.test_careers_overview.yaml
  tests/cassettes/TestRoutes.test_partners_pages.yaml
  tests/test_routes.py
Labels: Review: QA +1, Review: Code +1 (with changes)

#1011 Remove unnecessary div from logo sections
  templates/index.html
Labels: Review: Code +1, Review: QA +1

#1012 Update careers pages meta-image
  templates/base_index.html
  templates/careers/job-detail.html
  templates/partial/_footer.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#1015 Update careers index meta data
  templates/careers/index.html
Labels: Review: Code +1, Review: QA +1

#1017 WD-5826 Update Canonical logo
  templates/blog/article.html
Labels: Review: Code +1, Review: QA +1

#1018 Update _withdrawal_notification-email.html
  templates/careers/application/_withdrawal_notification-email.html
Labels: Review: Code +1

#1019 WD-5430 - Replace the broken favicon with a PNG version
  templates/base_index.html
Labels: Review: Code +1, Review: QA +1, Review: Design +1

#1009 [copy update] WD-5625 Update executive summit events
  static/sass/styles.scss
  templates/partners/executive-summit.html
Labels: Review: Code +1, Review: QA +1

#1023 WD-5431 - Add a 48x48 favicon
  templates/base_index.html
Labels: Review: Code needed, Review: QA needed

#1029 Fix application submission bug
  webapp/greenhouse.py
Labels: Review: Code +1

#1026 [copy update] /partners/find-a-partner
  templates/partners/find-a-partner.html
Labels: Review: Code +1, Review: QA +1
