Repository canonical/canonical.com, pull requests merged in 2023-11, with the labels that each got.

#1098 WD-6868 - Add the Open Documentation Academy page
  templates/documentation/_documentation-tab-navigation.html
  templates/documentation/open-documentation-academy.html
Labels: Review: Code +1, Review: QA +1, Review: Design +1

#1099 docs: update README.md license link
  README.md
Labels: Review: Code needed

#1094 [WD-6796] modify sections in /careers/engineering
  templates/careers/_base-department.html
  templates/careers/engineering.html
  templates/shared/_engineering-fast-track.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1, Review: Design +1

#1102 Add microcloud subnav and form
  static/sass/_pattern_global-nav.scss
  templates/microcloud/contact-us.html
  templates/microcloud/thank-you.html
  templates/partial/_microcloud-navigation.html
  templates/partial/_navigation.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1, Review: Design +1, Review: Marketing +1

#1109 Add modal and apply minor design updates to landing page
  templates/microcloud/_microcloud-modal.html
  templates/microcloud/index.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1, Review: Design +1

#1097 Add resources page and slider
  static/js/microcloud-slider.js
  static/sass/styles.scss
  templates/microcloud/resources.html
Labels: Review: QA +1, Review: UX +1, Review: Design +1, Review: Code +1 (with changes)

#1112 Fix modal bug and apply final changes
  static/sass/styles.scss
  templates/microcloud/_microcloud-modal.html
  templates/microcloud/index.html
  templates/microcloud/resources.html
  templates/microcloud/roadshow.html
  templates/partial/_microcloud-navigation.html
Labels: Review: Code +1, Review: QA +1

#1114 Apply code review
  static/js/microcloud-slider.js
  templates/microcloud/contact-us.html
  templates/microcloud/index.html
Labels: Review: Code +1

#1103 Microcloud refresh
  static/js/microcloud-slider.js
  static/js/typer.js
  static/sass/_pattern_animations.scss
  static/sass/_pattern_global-nav.scss
  static/sass/styles.scss
  templates/microcloud/_microcloud-modal.html
  templates/microcloud/contact-us.html
  templates/microcloud/index.html
  templates/microcloud/resources.html
  templates/microcloud/roadshow.html
  templates/microcloud/thank-you.html
  templates/partial/_microcloud-navigation.html
  templates/partial/_navigation.html
Labels: Review: Code +1 (with changes)

#1116 fix(microcloud) two typos in roadshow page ("MicroCoud" -> "MicroCloud")
  templates/microcloud/roadshow.html
Labels: Review: Code +1, Review: QA +1

#1117 move Jira config file to one level higher to make it work
  .github/.jira_sync_config.yaml
Labels: Review: Code +1

#1100 Fix application job post id
  templates/careers/base_job-details.html
  templates/careers/job-detail.html
  webapp/app.py
Labels: Review: Code +1, Review: QA +1

#1120 WD-7440 - update /silicon page
  templates/partners/silicon.html
Labels: Review: Code +1, Review: QA +1

#1123 WD-6363 MySQL page
  templates/data/mysql.html
  templates/partial/_data-navigation.html
Labels: Review: Code +1, Review: QA +1, Review: Design +1

#1130 WD-7587 - update /diversity page
  templates/careers/company-culture/diversity.html
Labels: Review: Code +1, Review: QA +1
