Repository canonical/canonical.com, pull requests merged in 2023-06, with the labels that each got.

#855 WD-3257 Update careers landing
  static/js/careers-filter-and-sort.js
  static/sass/_pattern_search-panel.scss
  static/sass/_pattern_strip.scss
  static/sass/styles.scss
  templates/base_index.html
  templates/careers/_search.html
  templates/careers/index.html
  templates/partial/_footer.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1, Review: Design +1

#880 WD-4367 Add help text to career applications form
  templates/careers/job-detail.html
  webapp/greenhouse.py
Labels: Review: Code +1, Review: QA +1

#882 WD-4421 Update application job name when transferring roles
  templates/careers/application/index.html
  templates/careers/application/partial/_assessment.html
  webapp/application.py
Labels: Review: Code +1, Review: QA +1

#865 WD-3107 build new executive summit page
  static/js/modals.js
  static/sass/styles.scss
  templates/partial/_navigation.html
  templates/partners/executive-summit.html
  templates/partners/partial/_executive-summit-form.html
  templates/shared/forms/_country.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1, Review: Design +1

#876 WD-3173 Build remote work
  redirects.yaml
  static/sass/styles.scss
  templates/careers/_search.html
  templates/careers/application/partial/_lifestyle.html
  templates/careers/company-culture.html
  templates/careers/company-culture/remote-work.html
  templates/careers/index.html
  templates/careers/sitemap.xml
  templates/careers/travel.html
  templates/partial/_navigation.html
  tests/test_routes.py
  webapp/app.py
Labels: Review: Code +1, Review: QA +1, Review: UX +1, Review: Design +1

#884 WD-3178 update URLs
  redirects.yaml
  templates/careers/company-culture/diversity.html
  templates/careers/company-culture/progression.html
  templates/careers/company-culture/sustainability.html
  templates/careers/sitemap.xml
  templates/partial/_navigation.html
  tests/test_routes.py
  webapp/app.py
Labels: Review: Code +1, Review: QA +1

#890 [copy update] WD-4529 update employee count
  templates/careers/company-culture.html
Labels: Review: Code needed, Review: QA needed

#887 Update /become-a-partner
  .stylelintrc
  static/sass/styles.scss
  templates/partners/become-a-partner.html
Labels: Review: UX needed, Review: QA +1, Review: Design +1, Review: Code +1 (with changes)

#893 Update /partners/ihv-and-oem
  templates/partners/ihv-and-oem.html
Labels: Review: UX needed, Review: Code +1, Review: QA +1, Review: Design +1

#886 Udpate /partners
  templates/partial/_partners-footer.html
  templates/partners/index.html
Labels: Review: UX needed, Review: Code +1, Review: QA +1, Review: Design +1

#889 Update /partners/desktop
  static/sass/styles.scss
  templates/partners/desktop.html
Labels: Review: QA +1, Review: UX +1, Review: Design +1, Review: Code +1 (with changes)

#896 Redesign /partners/public-cloud
  templates/partners/public-cloud.html
Labels: Review: QA +1, Review: UX +1, Review: Design +1, Review: Code +1 (with changes)

#904 Add redirect from identity to diversity
  redirects.yaml
Labels: Review: Code +1

#899 Update /partners/channel-and-reseller
  templates/partial/_breadcrumbs.html
  templates/partial/_partners-footer.html
  templates/partners/apps-and-snaps.html
  templates/partners/become-a-partner.html
  templates/partners/channel-and-reseller.html
  templates/partners/desktop.html
  templates/partners/devices-and-iot.html
  templates/partners/gsi.html
  templates/partners/ihv-and-oem.html
  templates/partners/index.html
  templates/partners/isv-partners.html
  templates/partners/kubernetes.html
  templates/partners/partial/_co-sell-with-canonical.html
  templates/partners/partial/_footer.html
  templates/partners/partial/_partners-logos.html
  templates/partners/public-cloud.html
  templates/projects/directory.html
  templates/projects/index.html
Labels: Review: UX needed, Review: Design needed, Review: QA +1, Review: Code +1 (with changes)

#897 Redesign /partners/iot-device
  templates/partners/iot-device.html
Labels: Review: QA +1, Review: UX +1, Review: Design +1, Review: Code +1 (with changes)

#917 Use PS5 registry
  konf/site.yaml
Labels: Review: Code +1

#919 WD-4752 - Update diversity content
  templates/careers/company-culture/diversity.html
Labels: Review: Code +1

#918 WD-4751 - Fix typo on the company culture page
  templates/careers/company-culture.html
Labels: Review: Code +1

#901 Update /partners/gsi
  static/sass/styles.scss
  templates/partners/channel-and-reseller.html
  templates/partners/desktop.html
  templates/partners/gsi.html
  templates/partners/ihv-and-oem.html
  templates/partners/partial/_partners-logos.html
Labels: Review: QA +1, Review: UX +1, Review: Design +1, Review: Code +1 (with changes)

#920 fix marketo payload fields
  templates/partners/become-a-partner.html
Labels: Review: Code +1, Review: QA +1

#921 WD-4817 - Remove Bazaar from products
  templates/projects/directory.html
  templates/projects/index.html
Labels: Review: Code +1

#910 Wd 4674 visual update partners pages footer
  templates/partners/iot-device.html
  templates/partners/partial/_footer.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#900 Change LXD product URL
  webapp/static_data.py
Labels: Review: Code +1

#911 Wd 3811 dev canonical com contact us
  templates/contact-us.html
Labels: Review: QA +1, Review: UX +1, Review: Code +1 (with changes)

#908 Projects
  templates/projects/index.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#909 Update /projetcs/directory
  static/sass/styles.scss
  templates/projects/directory.html
Labels: Review: QA +1, Review: UX +1, Review: Design +1

#916 Wd 3736 dev canonical com press centre
  templates/press-centre/card.html
  templates/press-centre/index.html
  templates/shared/_pagination.html
Labels: Review: QA +1, Review: UX +1, Review: Code +1 (with changes)

#912 Update error pages
  templates/401.html
  templates/404.html
  templates/500.html
  templates/502.html
  templates/_error.tmpl
  templates/base_index.html
  templates/partial/_footer.html
  templates/partners/partial/_footer.html
Labels: Review: UX needed, Review: QA +1, Review: Code +1 (with changes)

#894 Apply redesign /partners/find-a-partner and add new /silicon partner page
  static/js/find-a-partner.js
  static/sass/styles.scss
  templates/partial/_navigation.html
  templates/partners/find-a-partner.html
  templates/partners/partial/_partner-filters/_programme-filters.html
  templates/partners/partial/_partner-filters/_services-filters.html
  templates/partners/partial/_partner-filters/_technology-filters.html
  templates/partners/silicon.html
  webapp/app.py
Labels: Review: QA +1, Review: UX +1, Review: Design +1, Review: Code +1 (with changes)
