Repository canonical/canonical.com, pull requests merged in 2023-07, with the labels that each got.

#927 Revert "Update favicons, take 2"
  templates/base_index.html
Labels: Review: Code +1

#860 Update careers engineering fast track with new design
  static/sass/styles.scss
  templates/base_index.html
  templates/careers/engineering.html
  templates/shared/_engineering-fast-track.html
Labels: Review: UX needed, Review: QA +1, Review: Design +1, Review: Code +1 (with changes)

#875 WD-1154 Get hiring leads bio
  konf/site.yaml
  requirements.txt
  templates/careers/application/index.html
  tests/cassettes/TestApplicationPageHelpers.test_get_employee_directory_data.yaml
  tests/test_application.py
  webapp/app.py
  webapp/application.py
  webapp/hiring_leads.json
Labels: Review: Code +1, Review: QA +1

#926 WD-4941 - Add FAQ section about WI anonymously
  templates/careers/application/faq.html
Labels: Review: Code +1, Review: QA +1

#906 Update career progression images and text
  templates/careers/company-culture/progression.html
Labels: Review: Code +1, Review: QA +1, Review: Design +1

#931 WD-4982 - Make the navigation tag orange
  static/sass/styles.scss
Labels: Review: QA +1, Review: Code +1 (with changes)

#907 Documentation practice
  static/sass/styles.scss
  templates/documentation/_documentation-header.html
  templates/documentation/_documentation-tab-navigation.html
  templates/documentation/beyond-canonical.html
  templates/documentation/index.html
  templates/documentation/work-and-careers.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1, Review: Design +1

#898 canonical.com homepage
  .stylelintrc
  static/js/tabbed-content.js
  static/sass/_pattern_footer.scss
  static/sass/_pattern_lists.scss
  static/sass/_pattern_tabs.scss
  static/sass/styles.scss
  templates/base_index.html
  templates/careers/index.html
  templates/index.html
  templates/partial/_footer.html
  templates/partial/_navigation.html
  yarn.lock
Labels: Review: Design needed, Review: Code +1, Review: QA +1, Review: UX +1

#933 Update careers nav
  templates/partial/_navigation.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#934 Wd 4979 update copy in the press center page
  templates/press-centre/index.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#938 WD-5006 - Exclude blog posts with the tags lang:kr and lang:cm
  webapp/app.py
Labels: Review: Code +1

#922 WD-1174 fix identity and paths
  tests/cassettes/TestRoutes.test_careers_progression.yaml
  tests/cassettes/TestRoutes.test_company_culture_pages.yaml
  webapp/app.py
Labels: Review: Code +1, Review: QA +1

#941 Fix bug with late stage
  webapp/application.py
Labels: Review: Code +1

#915 Wd 4287 dev canonical com blog entry
  package.json
  static/sass/_pattern_blog-card.scss
  static/sass/_pattern_lists.scss
  static/sass/styles.scss
  templates/blog/article.html
  templates/blog/author.html
  templates/blog/blog-card-header.html
  templates/blog/blog-card.html
  templates/blog/featured-articles.html
  templates/blog/filters.html
  templates/blog/index.html
  templates/blog/newsletter-form.html
  templates/blog/tag.html
  templates/careers/company-culture/diversity.html
  templates/careers/company-culture/remote-work.html
  templates/careers/index.html
  templates/partial/_breadcrumbs.html
  templates/partners/executive-summit.html
  templates/partners/iot-device.html
  templates/partners/public-cloud.html
  templates/press-centre/index.html
  templates/shared/_pagination.html
  yarn.lock
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#939 WD-5009 - Improve the withdrawal email to include current stage
  templates/careers/application/_withdrawal_notification-email.html
  webapp/application.py
Labels: Review: Code +1, Review: QA +1

#942 Apply copy updates
  templates/partners/thank-you.html
  templates/projects/index.html
Labels: Review: Code +1, Review: QA +1

#947 Fix careers bugs/styling issues
  static/sass/styles.scss
  templates/careers/_careers-pagination.html
  templates/careers/_search.html
  templates/careers/company-culture/sustainability.html
  templates/shared/_featured_jobs.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#955 Partner changes
  templates/partners/index.html
Labels: Review: Code +1, Review: QA +1

#954 Update /press-centre headings
  templates/press-centre/index.html
Labels: Review: Code +1

#953 Apply nav updates
  static/js/navigation.js
  static/sass/styles.scss
  templates/index.html
  templates/partial/_navigation.html
Labels: Review: Code +1, Review: QA +1, Review: Design +1

#958 Update footer link list padding
  templates/partial/_footer.html
Labels: Review: Code +1, Review: QA +1, Review: Design +1

#961 Add spacing to author names
  templates/documentation/work-and-careers.html
Labels: Review: Code needed, Review: QA needed

#960 Update partner images
  static/sass/styles.scss
  templates/partners/ihv-and-oem.html
  templates/partners/iot-device.html
Labels: Review: Code +1, Review: QA +1, Review: Design +1

#956 Optimise suru image and avoid layout shift
  templates/careers/company-culture/diversity.html
  templates/careers/index.html
  templates/index.html
  templates/press-centre/index.html
Labels: Review: Code +1, Review: QA +1

#962 Update tab img
  templates/index.html
Labels: Review: Code +1, Review: QA +1, Review: Design +1

#964 Filter out nec logo
  templates/partners/partial/_partners-logos.html
Labels: Review: Code +1, Review: QA +1, Review: Design +1

#965 Visual fixes
  static/sass/styles.scss
  templates/careers/company-culture.html
  templates/index.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#951 WD-4092 Update careers departments
  templates/careers/_base-department.html
  templates/careers/administration.html
  templates/careers/commercial-operations.html
  templates/careers/company-culture/index.html
  templates/careers/company-culture/progression.html
  templates/careers/engineering.html
  templates/careers/finance.html
  templates/careers/legal.html
  templates/careers/marketing.html
  templates/careers/people.html
  templates/careers/product.html
  templates/careers/project-management.html
  templates/careers/sales.html
  templates/careers/support-engineering.html
  templates/careers/web-and-design.html
  templates/shared/_promoted_roles.html
  webapp/app.py
Labels: Review: QA +1, Review: Code +1 (with changes)

#969 Update the theme color to #262626
  templates/base_index.html
Labels: Review: Code +1, Review: QA +1

#971 Fix MicroK8s typo
  templates/index.html
Labels: Review: Code +1, Review: QA +1

#968 Clean up custom styles
  static/sass/_pattern_animations.scss
  static/sass/_pattern_buttons.scss
  static/sass/_pattern_cards.scss
  static/sass/_pattern_footer.scss
  static/sass/_pattern_headings.scss
  static/sass/_pattern_lists.scss
  static/sass/_pattern_search-form.scss
  static/sass/_pattern_strip.scss
  static/sass/styles.scss
  templates/_error.tmpl
  templates/base_index.html
  templates/blog/article.html
  templates/blog/author.html
  templates/blog/index.html
  templates/blog/tag.html
  templates/careers/company-culture/diversity.html
  templates/careers/company-culture/remote-work.html
  templates/careers/index.html
  templates/contact-us.html
  templates/index.html
  templates/partners/become-a-partner.html
  templates/partners/channel-and-reseller.html
  templates/partners/desktop.html
  templates/partners/executive-summit.html
  templates/partners/find-a-partner.html
  templates/partners/gsi.html
  templates/partners/ihv-and-oem.html
  templates/partners/index.html
  templates/partners/iot-device.html
  templates/partners/public-cloud.html
  templates/partners/silicon.html
  templates/press-centre/index.html
  templates/projects/directory.html
  templates/projects/index.html
Labels: Review: Code +1, Review: QA +1

#974 WD-5154 - Add space between words on small screens
  templates/index.html
Labels: Review: Code +1, Review: QA +1

#983 Fix double body class declaration
  templates/blog/article.html
Labels: Review: Code +1, Review: QA +1

#959 candidate page: add executive review to late stage
  templates/careers/application/partial/_late-stage.html
Labels: Review: Code +1, Review: QA +1

#980 Fix blog department pages
  templates/careers/_base-department.html
  templates/careers/administration.html
  templates/careers/commercial-operations.html
  templates/careers/engineering.html
  templates/careers/ethics.html
  templates/careers/finance.html
  templates/careers/legal.html
  templates/careers/marketing.html
  templates/careers/people.html
  templates/careers/product.html
  templates/careers/project-management.html
  templates/careers/support-engineering.html
  templates/careers/web-and-design.html
  templates/projects/index.html
Labels: Review: Code +1, Review: QA +1

#985 Fix typos in interview-done card
  templates/careers/application/_interview-card-done.html
Labels: Review: Code +1

#986 Fix 404 Redirect enterprise services to Ubuntu Pro
  redirects.yaml
Labels: Review: Code +1, Review: QA +1

#990 Update partners nav item
  templates/partial/_navigation.html
Labels: Review: Code +1, Review: QA +1

#988 WD-5254 Careers copy updates
  templates/careers/company-culture/diversity.html
  templates/careers/company-culture/progression.html
  templates/careers/company-culture/remote-work.html
  templates/careers/company-culture/sustainability.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#991 Update /company-culture copy
  templates/careers/company-culture/index.html
Labels: Review: QA +1, Review: Code +1 (with changes)
