Repository canonical/canonical.com, pull requests merged in 2023-02, with the labels that each got.

#774 Update address copy on /contact-us
  templates/contact-us.html
Labels: Review: Code +1

#777 Update copy for selected department pages
  templates/careers/engineering.html
  templates/careers/finance.html
  templates/careers/people.html
  templates/careers/project-management.html
  templates/careers/web-and-design.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#775 Fix search width and featured roles copy
  static/sass/_pattern_search-form.scss
  static/sass/styles.scss
  templates/shared/_fast_track_jobs.html
  templates/shared/_featured_jobs.html
Labels: Review: Code +1, Review: QA +1, Review: Design +1

#779 Include departments with no vacancies
  redirects.yaml
  templates/careers/administration.html
  templates/careers/legal.html
  templates/careers/thank-you.html
  templates/index.html
  templates/partial/_navigation.html
  webapp/app.py
  webapp/greenhouse.py
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#781 Redirect to correct intellectual property page
  redirects.yaml
Labels: Review: Code +1, Review: QA +1

#780 Add link with circle of products image to the products page
  templates/index.html
Labels: Review: QA +1, Review: UX +1, Review: Code +1 (with changes)

#783 WD-1537 Update the application FAQ content
  templates/careers/application/faq.html
Labels: Review: Code +1, Review: QA +1

#787 WD-1521 Update the legal content
  templates/careers/legal.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#784 WD-1534 Update support engineering copy
  templates/careers/support-engineering.html
Labels: Review: Code +1, Review: QA +1

#785 WD-1533 Update Sales copy
  templates/careers/sales.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#776 Create new /documentation pages
  static/js/side-navigation.js
  static/sass/styles.scss
  templates/documentation/_documentation-header.html
  templates/documentation/_documentation-tab-navigation.html
  templates/documentation/beyond-canonical.html
  templates/documentation/documentation-layout.html
  templates/documentation/index.html
  templates/documentation/work-and-careers.html
  templates/partial/_navigation.html
  templates/practice/documentation.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1, Review: Design +1, Review: PdM +1, Review: A11y +1

#786 WD-1522 Update Marketing copy
  templates/careers/marketing.html
Labels: Review: Code +1, Review: QA +1

#790 Update meta-description on /documentation
  templates/documentation/index.html
Labels: Review: Code +1, Review: QA +1

#791 Update to /documentation/working-and-careers
  templates/documentation/work-and-careers.html
Labels: Review: Code +1

#792 Product department page build
  redirects.yaml
  templates/careers/product.html
Labels: Review: QA +1, Review: UX +1, Review: Code +1 (with changes)

#782 WD-1517 Update the Administration copy
  templates/careers/administration.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1, Review: Design +1

#799 WD-2112 Centrally align the application form
  static/sass/_pattern_cards.scss
  templates/careers/base_job-details.html
  templates/careers/job-detail.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1, Review: Design +1

#800 WD-2112 Small fixes on top of https://github.com/canonical/canonical.com/pull/799
  templates/careers/base_job-details.html
Labels: Review: Code needed, Review: QA needed

#801 WD-2116 make search work with lower and upper case
  static/js/find-a-partner.js
Labels: Review: Code +1, Review: QA +1

#805 Remove the job description overriding styling
  static/sass/styles.scss
Labels: Review: Code +1, Review: QA +1

#804 Fix z-indexing on /documentation
  static/sass/styles.scss
  templates/documentation/beyond-canonical.html
  templates/documentation/index.html
  templates/documentation/work-and-careers.html
Labels: Review: Code +1, Review: QA +1

#806 WD-2138 Remove the fast track roles from departments pages
  templates/shared/_promoted_roles.html
Labels: Review: Code +1, Review: QA +1

#802 Remove hardcoded qq.com
  webapp/app.py
Labels: Review: Code +1

#796 WD-2031 Add a no roles message to careers departments with no open roles
  static/js/careers-filter-and-sort.js
  templates/partial/_careers-available-roles.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1, Review: Design +1
