Repository canonical/canonical.com, pull requests merged in 2024-10, with the labels that each got.

#1383 Create /solutions/telco/5g-edge webpage
  secondary-navigation.yaml
  templates/sitemap-links.xml
  templates/solutions/telco/5g-core.html
  templates/solutions/telco/5g-edge.html
  templates/solutions/telco/_form-telco-5g.html
Labels: Review: QA +1, Review: UX +1, Review: Design +1, Review: Code +1 (with changes)

#1387 fix: incorrect usage of p-rule on secure open source page
  templates/solutions/secure-open-source/index.html
Labels: Review: Code +1, Review: QA +1, Bug 🐛

#1388 Fix download link
  templates/solutions/secure-open-source/index.html
Labels: Review: Code +1, Review: QA +1

#1386 feat: /data/valkey and corresponding modal
  secondary-navigation.yaml
  templates/data/_form-data-valkey.html
  templates/data/valkey.html
  templates/partial/_data-navigation.html
  templates/partial/_lxd-navigation.html
  templates/partial/_microcloud-navigation.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1, Review: Design +1, Review: PdM +1

#1385 Add new pages to /solutions/telco bubble
  secondary-navigation.yaml
  templates/data/_form-data-relational-dbs.html
  templates/macros/quote_wrapper.jinja
  templates/sitemap-links.xml
  templates/solutions/telco/5g-core.html
  templates/solutions/telco/5g-edge.html
  templates/solutions/telco/_form-telco-5g.html
Labels: Review: QA +1, Review: Design +1

#1391 Update form id for telco-5g and quote macro
  templates/macros/quote_wrapper.jinja
  templates/solutions/telco/_form-telco-5g.html
Labels: Review: QA +1

#1390 Add parent path to secondary navigation
  secondary-navigation.yaml
  templates/navigation/secondary-navigation.html
  webapp/navigation.py
Labels: Review: Code +1, Review: QA +1

#1395 Add managed postgresql page
  secondary-navigation.yaml
  templates/data/postgresql/managed.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1, Review: Design +1

#1379 WD-13863 - add form template to c.com
  static/files/forms-data.json
  static/js/forms.js
  static/js/modals.js
  static/js/prepare-form-inputs.js
  static/sass/_pattern_forms.scss
  templates/base_index.html
  templates/shared/forms/form-fields.html
  templates/shared/forms/form-template.html
  webapp/app.py
Labels: Review: Code +1, Review: QA +1

#1392 feat: /data/kafka refresh
  templates/data/_form-data-kafka.html
  templates/data/kafka.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1, Review: Design +1

#1394 feat: /openstack landing page
  templates/openstack/index.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1, Review: Design +1

#1400 feat: /solutions/open-ran build
  secondary-navigation.yaml
  templates/solutions/telco/index.html
  templates/solutions/telco/open-ran.html
Labels: Review: QA +1, Review: UX +1, Review: Design +1, Review: Code +1 (with changes)

#1398 Update data bubble navigation
  secondary-navigation.yaml
  webapp/app.py
Labels: Review: Code +1, Review: QA +1

#1403 WD-15046 Dev Created /data/support/spark
  templates/data/sitemap.xml
  templates/data/spark/index.html
  templates/data/spark/support.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1, Review: Design +1

#1402 Dev created /solutions/ai/genai
  secondary-navigation.yaml
  templates/shared/forms/_country.html
  templates/solutions/ai/_form-ai.html
  templates/solutions/ai/genai.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1, Review: Design +1

#1407 WD-15274 - company/about new page
  .djlintrc
  navigation.yaml
  static/js/locations-map.js
  templates/careers/company-culture/remote-work.html
  templates/company/index.html
  templates/sitemap-links.xml
Labels: Review: Code +1, Review: QA +1, Review: UX +1, Review: Design +1

#1412 Update data/postgresql/support title
  templates/data/postgresql/support.html
Labels: Review: Code +1, Review: QA +1
