Repository canonical/canonical.com, pull requests merged in 2024-03, with the labels that each got.

#1195 WD-9331 - add missing asterisk to Country field
  templates/shared/forms/_country.html
  templates/solutions/_form_infrastructure.html
Labels: Review: Code +1, Review: QA +1

#1189 Add the Enterprise Sales Representative video to the candidate page
  templates/careers/application/index.html
  webapp/application.py
Labels: Review: Code +1, Review: QA +1

#1198 WD-9422 - remove section from /diversity
  templates/careers/company-culture/diversity.html
Labels: Review: Code +1, Review: QA +1

#1199 WD-9253 - add buttons to /documentation
  templates/documentation/open-documentation-academy.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#1202 [WD-9557] add links to datasheets in /data/mongodb
  templates/data/mongodb.html
Labels: Review: Code +1, Review: QA +1

#1204 WD-9572 Update written interview FAQs
  templates/careers/application/faq.html
Labels: Review: Code +1, Review: QA +1

#1188 auto delete interviews on withdrawal (WD-7721)
  .env
  .github/workflows/pr.yaml
  Dockerfile
  konf/site.yaml
  requirements.txt
  templates/careers/application/_withdrawal-feedback-not-needed-email.html
  templates/careers/application/_withdrawal-interview-canceled-email.html
  templates/careers/application/_withdrawal_notification-email.html
  templates/careers/application/withdrawal.html
  tests/test_application.py
  tests/test_google_calendar.py
  webapp/application.py
  webapp/google_calendar.py
Labels: Review: Code +1, Review: QA +1

#1207 Add logic for loading-spinner on forms
  static/js/forms.js
  templates/base_index.html
Labels: Review: Code +1, Review: QA +1

#1205 update data fabric pages with bigger logos
  static/sass/styles.scss
  templates/data/kafka.html
  templates/data/mongodb.html
  templates/data/mysql.html
  templates/data/opensearch.html
  templates/data/postgresql.html
  templates/data/spark.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#1211 Pause Google Calendar API Usage
  tests/test_application.py
  tests/test_google_calendar.py
  webapp/application.py
Labels: Review: Code +1

#1213 WD-9413 - add new /identity page
  redirects.yaml
  static/sass/styles.scss
  templates/careers/company-culture/diversity.html
  templates/careers/company-culture/identity.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1, Review: Design +1

#1221 [WD-9668] remove one tab and change content on /solutions/telco
  templates/solutions/telco/index.html
  templates/solutions/telco/tabs/_telco-control-upgrades-tab.html
  templates/solutions/telco/tabs/_telco-highest-level-compliance-tab.html
Labels: Review: Code needed, Review: QA needed

#1224 Add djLint formatter/linter for Jinja templates
  .djlintrc
  .github/workflows/pr.yaml
  package.json
  requirements.txt
  templates/solutions/telco/index.html
Labels: Review: Code +1, Review: QA +1

#1226 Fix Candidate Reports Download Issue (WD-9878)
  static/js/applications/get-report.js
Labels: Review: Code +1, Review: QA +1

#1222 Build /solutions/ai + modal
  static/sass/styles.scss
  templates/solutions/_form_infrastructure.html
  templates/solutions/ai/_form-ai.html
  templates/solutions/ai/index.html
  templates/solutions/big-data-ai/_form-big-data-ai.html
  templates/solutions/big-data-ai/index.html
  templates/solutions/infrastructure/_form_infrastructure.html
  templates/solutions/infrastructure/index.html
Labels: Review: QA +1, Review: UX +1, Review: Design +1, Review: Code +1 (with changes), Review: PdM +1

#1229 Update AI/ML-ops link on index to point toward internal page
  templates/index.html
Labels: Review: Code +1, Review: QA +1

#1230 Updated cookie policy to v3.6.0
  package.json
  yarn.lock
Labels: Review: Code +1, Review: QA +1
