Repository canonical/canonical.com, pull requests merged in 2024-09, with the labels that each got.

#1363 update email prompt for candidate page
  templates/careers/application/_withdrawal-form.html
  templates/careers/application/partial/_assessment.html
Labels: Review: Code +1

#1362 WD-13772 Refresh /data/postgresql
  templates/data/postgresql.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1, Review: Design +1

#1369 WD-13515 Dev Create /openstack/architecture
  static/sass/styles.scss
  templates/openstack/architecture.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1, Review: Design +1

#1364 Wd 13776 Dev Refresh /data/mysql
  templates/data/mongodb/index.html
  templates/data/mysql.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1, Review: Design +1

#1370 Fix application question field
  templates/careers/job-detail.html
Labels: Review: Code +1, Review: QA +1

#1365 Add is-required label to required fields
  templates/data/_form-data-kafka.html
  templates/data/_form-data-mongodb.html
Labels: Review: QA +1

#1368 feat: Build /what-is-postgresql page
  package.json
  static/sass/styles.scss
  templates/data/postgresql/index.html
  templates/data/postgresql/what-is-postgresql.html
  templates/data/sitemap.xml
  yarn.lock
Labels: Review: QA +1, Review: Design +1, Review: Code +1 (with changes)

#1367 Use local sessions and cipher
  tests/test_application.py
  webapp/app.py
  webapp/application.py
  webapp/google_calendar.py
  webapp/greenhouse.py
  webapp/requests_session.py
Labels: Review: Code +1, Review: QA +1

#1372 WD-14408 - add assets on /solutions/ubuntu-os
  templates/solutions/ubuntu-os/index.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1 (with changes)

#1374 chore: Upgrade canonicalwebteam.search to 2.1.1
  requirements.txt
  webapp/app.py
Labels: Review: Code +1, Review: QA +1

#1375 Update desktop installer contact to Oliver Smith
  templates/projects/directory.html
Labels: Review: Code +1, Review: QA +1

#1378 WD-15180 Added secondary navigation for /data/* pages
  secondary-navigation.yaml
Labels: Review: Code +1, Review: QA +1

#1377 chore: Update links in navigation.yaml & add link to copydoc
  navigation.yaml
Labels: Review: Code +1, Review: QA +1

#1380 Create /solutions/telco/5g-core webpage
  secondary-navigation.yaml
  templates/data/_form-data-relational-dbs.html
  templates/macros/quote_wrapper.jinja
  templates/solutions/telco/5g-core.html
  templates/solutions/telco/_form-telco-5g-core.html
Labels: Review: QA +1, Review: UX +1, Review: Design +1, Review: Code +1 (with changes)

#1382 chore: Update copy on /hiring-process
  templates/careers/hiring-process/index.html
Labels: Review: Code +1, Review: QA +1
