Repository canonical/canonical.com, pull requests merged in 2024-06, with the labels that each got.

#1265 WD-11799 - fix homepage modal styling
  static/js/modals.js
  static/sass/_pattern_homepage-modal.scss
  static/sass/styles.scss
  templates/partners/partial/_homepage-form.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1, Review: Design +1

#1267 Update contact form success banner
  templates/solutions/ai/index.html
  templates/solutions/big-data-ai/index.html
  templates/solutions/secure-open-source/index.html
Labels: Review: Code needed, Review: QA needed

#1272 Update datasheet
  templates/data/opensearch.html
Labels: Review: Code +1, Review: QA +1

#1273 WD-11979 copy update
  templates/lxd/manage.html
Labels: Review: Code +1, Review: QA +1

#1270 WD-10729 - update contact form
  static/js/modals.js
  static/sass/_pattern_forms.scss
  templates/partners/partial/_homepage-form.html
Labels: Review: UX needed, Review: QA +1, Review: Design +1, Review: Code +1 (with changes)

#1274 Implement country code to contact fields
  build.js
  package.json
  scripts/build-modules.sh
  static/files/countries.json
  static/files/timezones.json
  static/js/career-explorer/components/SelectableCard/SelectableCard.tsx
  static/js/career-explorer/components/SelectableCards/SelectableCards.tsx
  static/js/career-explorer/components/SelectedSkills/SelectedSkills.test.tsx
  static/js/career-explorer/components/SelectedSkills/SelectedSkills.tsx
  static/js/forms.js
  static/js/prepare-form-inputs.js
  static/sass/_pattern_forms.scss
  static/sass/styles.scss
  templates/base_index.html
  tsconfig.json
  webapp/app.py
  yarn.lock
Labels: Review: QA +1, Review: Code +1 (with changes)

#1276 Fix landing form submission
  templates/partners/partial/_homepage-form.html
Labels: Review: Code needed, Review: QA needed

#1279 Update copy /solutions/big-data-ai
  templates/solutions/big-data-ai/index.html
Labels: Review: Code +1, Review: QA +1

#1281 Update copy /solutions/ai-infrastructure
  templates/solutions/ai-infrastructure/index.html
Labels: Review: Code +1, Review: QA +1

#1282 Fixed Naming for templates
  templates/careers/company-culture/diversity.html
  templates/careers/company-culture/identity.html
  templates/careers/company-culture/index.html
  templates/careers/company-culture/progression.html
Labels: Review: Code +1, Review: QA +1

#1283 bug: Fix broken link to jaas.ai on '/projects'
  templates/projects/index.html
Labels: Review: Code +1, Review: QA +1

#1280 feat: Build '/solutions/sovereign-cloud' page and modal form
  templates/solutions/sovereign-cloud/_form-sovereign-cloud.html
  templates/solutions/sovereign-cloud/index.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1, Review: Design +1
