Repository canonical/canonical.com, pull requests merged in 2024-11, with the labels that each got.

#1413 bug: Fix seperators and remove stale custom styles
  static/sass/styles.scss
  templates/careers/_base-department.html
  templates/careers/company-culture/index.html
Labels: Review: Code +1, Review: QA +1

#1404 New /data/kafka bubble pages
  secondary-navigation.yaml
  templates/data/_form-data-kafka.html
  templates/data/kafka.html
  templates/data/kafka/index.html
  templates/data/kafka/managed.html
  templates/data/kafka/support.html
  templates/data/kafka/what-is-kafka.html
Labels: Review: Code +1 (with changes)

#1420 bug: Fix missing subnav
  secondary-navigation.yaml
Labels: Review: Code +1, Review: QA +1

#1418 specify timeouts on all http requests
  webapp/app.py
  webapp/google_calendar.py
  webapp/greenhouse.py
  webapp/partners.py
Labels: Review: Code +1, Review: QA +1

#1423 copy update: /data/mongodb/support
  templates/data/mongodb/support.html
Labels: Review: Code +1, Review: QA +1

#1428 [WD-16470] Page refresh microcloud
  secondary-navigation.yaml
  templates/microcloud/index.html
  templates/navigation/secondary-navigation.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1, Review: Design +1

#1426 Copy update: [WD-16878] Update /secure-open-source and Meganav
  navigation.yaml
  redirects.yaml
  templates/solutions/ai/infrastructure/index.html
  templates/solutions/open-source-security/_form-open-source-security.html
  templates/solutions/open-source-security/index.html
Labels: Review: QA +1

#1431 fix: apply fix for search being submit-able
  static/js/forms.js
  static/js/modals.js
  templates/careers/job-detail.html
  templates/data/_data-form.html
  templates/data/_form-data-kafka.html
  templates/data/_form-data-mongodb.html
  templates/data/_form-data-opensearch.html
  templates/data/_form-data-relational-dbs.html
  templates/data/_form-data-spark.html
  templates/data/_form-data-valkey.html
  templates/data/postgresql/managed.html
  templates/data/postgresql/support.html
  templates/lxd/_form-lxd-install.html
  templates/microcloud/_microcloud-modal.html
  templates/microcloud/contact-us.html
  templates/microcloud/index.html
  templates/navigation/navigation.html
  templates/partners/become-a-partner.html
  templates/partners/find-a-partner.html
  templates/partners/partial/_executive-summit-form.html
  templates/partners/partial/_homepage-form.html
  templates/partners/request-login.html
  templates/shared/forms/form-template.html
  templates/solutions/ai/_form-ai.html
  templates/solutions/ai/big-data-ai/_form-big-data-ai.html
  templates/solutions/ai/big-data-ai/index.html
  templates/solutions/ai/infrastructure/_form-ai-infrastructure.html
  templates/solutions/infrastructure/_form_infrastructure.html
  templates/solutions/open-source-security/_form-open-source-security.html
  templates/solutions/sovereign-cloud/_form-sovereign-cloud.html
  templates/solutions/telco/_form-telco-5g.html
  templates/solutions/ubuntu-os/_form-ubuntu-os.html
Labels: Review: Code +1, Review: QA +1

#1432 chore: Refresh valkey page
  templates/data/valkey.html
Labels: Review: Code +1, Review: QA +1, Review: Design +1

#1434 fix: candidate dashboard step counter
  static/sass/_pattern_application.scss
Labels: Review: Code +1, Review: QA +1

#1437 Rebrand /multipass landing page
  secondary-navigation.yaml
  templates/multipass/index.html
Labels: Review: Code +1, Review: QA +1, Review: Design +1

#1438 feat: Migrate microstack.run to canonical.com/microstack WD-16625
  build.js
  navigation.yaml
  secondary-navigation.yaml
  static/js/osselector.js
  templates/microstack/docs/document.html
  templates/microstack/docs/search-results.html
  templates/microstack/index.html
  webapp/app.py
Labels: Review: Code +1, Review: QA +1, Review: Design +1

#1393 Feature openstack
  navigation.yaml
  secondary-navigation.yaml
  static/sass/styles.scss
  templates/openstack/_form-openstack.html
  templates/openstack/architecture.html
  templates/openstack/index.html
Labels: Review: QA +1

#1445 fix the link to copy doc for /openstack
  templates/openstack/index.html
Labels: Review: QA +1

#1440 Migrate multipass docs pages
  templates/multipass/docs/document.html
  templates/multipass/docs/search-results.html
  webapp/app.py
Labels: Review: Code +1, Review: QA +1

#1425 copy update: /data/opensearch/support
  templates/data/opensearch/support.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1
