Repository canonical/canonical.com, pull requests merged in 2024-12, with the labels that each got.

#1453 feat: /openstack/architecture copy update
  templates/openstack/architecture.html
Labels: Review: Code +1, Review: QA +1

#1452 fix(/solutions/infrastructure): copy updates and conversion BE -> AE [WD-17391]
  templates/solutions/infrastructure/index.html
Labels: Review: Code +1, Review: QA +1

#1454 /partners/executive-summit copy updates
  templates/partners/executive-summit.html
Labels: Review: Code +1, Review: QA +1

#1448 fix(openstack): copy updates (including BE -> AE spelling), logos [WD-17510]
  templates/openstack/index.html
Labels: Review: Code +1, Review: QA +1, Review: Design +1

#1449 Add a testimonial to open source security page
  templates/solutions/open-source-security/index.html
Labels: Review: Code +1, Review: QA +1, Review: Design +1

#1443 Fix forms generator bugs
  static/files/forms-data.json
  static/js/modal.js
  static/js/modals.js
  templates/data/_form-data-relational-dbs.html
  templates/data/postgresql/index.html
  templates/shared/forms/form-fields.html
  templates/shared/forms/form-template.html
  webapp/app.py
Labels: Review: Code +1, Review: QA +1

#1460 [WD-17291] replace heavy images in navigation with lighter versions
  navigation.yaml
Labels: Review: QA +1

#1459 Update latest Multipass release
  static/files/latest-multipass-releases.json
Labels: Review: Code +1, Review: QA +1

#1463 [WD-17699] Copy update on homepage
  templates/index.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#1465 WD-17849 Copy-Update /lxd/manage
  templates/lxd/manage.html
Labels: Review: Code +1, Review: QA +1

#1464 chore: Apply copy changes to /openstack/architecture
  templates/openstack/architecture.html
Labels: Review: Code +1, Review: QA +1

#1466 feat: Install and implement discourse-rad-parser in _docs.html template
  package.json
  scripts/build-modules.sh
  templates/docs/shared/_docs.html
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#1468 WD-17850 Copy update on the Docs link at /lxd page
  secondary-navigation.yaml
Labels: Review: Code +1, Review: QA +1

#1461 copy update: /careers/company-culture
  templates/careers/company-culture/index.html
Labels: Review: Code +1, Review: QA +1

#1472 feat: Add childrenPaths to form template for shared forms
  static/files/forms-data.json
  templates/data/postgresql/managed.html
  templates/data/postgresql/support.html
  templates/data/postgresql/what-is-postgresql.html
  templates/shared/forms/form-fields.html
  webapp/app.py
Labels: Review: Code +1, Review: QA +1

#1469 chore(/openstack/architecture): Replace image used for 'Openstack under the hood'
  templates/openstack/architecture.html
Labels: Review: Code +1, Review: QA +1

#1471 feat: Add table of contents to doc pages
  templates/docs/shared/_docs.html
Labels: Review: Code +1, Review: QA +1, Review: Design +1

#1473 [WD-17927] Copy update on data/spark
  templates/data/spark/what-is-spark.html
Labels: Review: Code +1, Review: QA +1
