Repository canonical/canonical.com, pull requests merged in 2024-01, with the labels that each got.

#1150 WD-7800 - adjust job search field
  templates/careers/_search.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#1154 ISV partners revamp
  templates/partial/_standard-navigation.html
  templates/partners/index.html
  templates/partners/isv-partners.html
  templates/partners/partial/_footer.html
Labels: Review: QA +1, Review: UX +1, Review: Design +1, Review: Code +1 (with changes)

#1155 Fix multiple url params not persisting when linked to
  static/js/careers-filter-and-sort.js
  static/js/careers-progression.js
  static/js/file-validation.js
  static/js/find-a-partner.js
  static/js/microcloud-slider.js
  static/js/side-navigation.js
  static/js/source-inheritance.js
  static/js/sprint-map.js
  static/js/tabbed-content.js
  static/js/typer.js
  static/sass/_pattern_animations.scss
  static/sass/_pattern_cards.scss
  static/sass/_pattern_careers-progression.scss
  static/sass/_pattern_footer.scss
  static/sass/_pattern_forms.scss
  static/sass/_pattern_global-nav.scss
  static/sass/_pattern_search-panel.scss
  static/sass/styles.scss
Labels: Review: Code +1, Review: QA +1

#1156 Display the full name in a candidate withdrawal email
  webapp/application.py
Labels: Review: Code +1

#1159 /solutions/big-data-ai correct copy doc link
  templates/solutions/big-data-ai.html
Labels: Review: Code +1, Review: QA +1

#1158 WD-8178 - get in touch forms updated
  static/js/modals.js
  templates/contact-us.html
  templates/data/index.html
  templates/data/kafka.html
  templates/data/mongodb.html
  templates/data/mysql.html
  templates/data/opensearch.html
  templates/data/postgresql.html
  templates/data/relational-databases.html
  templates/data/spark.html
  templates/lxd/index.html
  templates/lxd/install.html
  templates/lxd/manage.html
  templates/microcloud/index.html
  templates/microcloud/roadshow.html
  templates/partners/partial/_homepage-form.html
  templates/solutions/big-data-ai.html
Labels: Review: Code +1, Review: QA +1

#1163 [WD-6157] add link to download datasheet to /data/opensearch
  templates/data/opensearch.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#1162 Build new Spark on K8s page
  .github/workflows/pr.yaml
  templates/data/spark-on-kubernetes.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1
