Repository canonical/canonical.com, pull requests merged in 2024-08, with the labels that each got.

#1315 WD-12234 Created /data/opensearch/support
  templates/data/opensearch/support.html
  templates/data/sitemap.xml
Labels: Review: QA +1, Review: UX +1, Review: Design +1, Review: Code +1 (with changes)

#1324 Creation of OpenSearch Pages
  Dockerfile
  templates/data/_form-data-opensearch.html
  templates/data/opensearch.html
  templates/data/opensearch/index.html
  templates/data/opensearch/managed.html
  templates/data/opensearch/support.html
  templates/data/opensearch/what-is-opensearch.html
  templates/data/sitemap.xml
Labels: Review: QA +1

#1329 Revert "Creation of OpenSearch Pages"
  Dockerfile
  templates/data/_form-data-opensearch.html
  templates/data/opensearch.html
  templates/data/opensearch/index.html
  templates/data/opensearch/managed.html
  templates/data/opensearch/support.html
  templates/data/opensearch/what-is-opensearch.html
  templates/data/sitemap.xml
Labels: Review: QA needed

#1332 /solutions/ubuntu-os copy updates
  templates/solutions/ubuntu-os/index.html
Labels: Review: Code +1, Review: QA +1

#1325 Implement logic to fetch and auto fill career roles
  navigation.yaml
  static/js/navigation/careers/Worker_populate-careers.js
  static/js/navigation/careers/populate-careers-roles.js
  static/js/navigation/main.js
  static/sass/_pattern_navigation.scss
  static/sass/styles.scss
  templates/navigation/_dropdown.html
  templates/navigation/partials/_list-item.html
Labels: Review: Code +1, Review: QA +1

#1322 Implement the Jinja logic for the desktop navigations dropdowns
  navigation.yaml
  requirements.txt
  static/js/modals.js
  static/js/navigation/careers/Worker_populate-careers.js
  static/js/navigation/careers/populate-careers-roles.js
  static/js/navigation/main.js
  static/js/prepare-form-inputs.js
  static/sass/_pattern_application.scss
  static/sass/_pattern_homepage-modal.scss
  static/sass/_pattern_navigation.scss
  static/sass/styles.scss
  templates/navigation/_dropdown.html
  templates/navigation/partials/_link-list.html
  templates/navigation/partials/_list-item.html
  templates/navigation/partials/_preview-links.html
  templates/navigation/partials/_primary-links.html
  templates/navigation/partials/_tab-panel.html
  webapp/app.py
  webapp/navigation.py
Labels: Review: Code +1, Review: QA +1

#1330 Creation of OpenSearch Pages
  Dockerfile
  templates/data/_form-data-opensearch.html
  templates/data/opensearch.html
  templates/data/opensearch/index.html
  templates/data/opensearch/managed.html
  templates/data/opensearch/support.html
  templates/data/opensearch/what-is-opensearch.html
  templates/data/sitemap.xml
Labels: Review: QA +1

#1334 WD-13370 Bumped cookie-policy to v3.6.4
  package.json
  yarn.lock
Labels: Review: QA +1

#1331 WD-13887 Add "Distributor" to programme filter of partners
  templates/partners/partial/_partner-filters/_programme-filters.html
Labels: Review: Code +1, Review: QA +1

#1338 WD-14016 CopyUpdate
  templates/solutions/ubuntu-os/index.html
Labels: Review: Code +1, Review: QA +1

#1337 Implement design changes for mobile view
  navigation.yaml
  package.json
  static/sass/_pattern_navigation.scss
  templates/navigation/_dropdown.html
  templates/navigation/dropdown.html
  templates/navigation/partials/_dropdown-desktop.html
  templates/navigation/partials/_dropdown-mobile.html
  templates/navigation/partials/_link-list.html
  templates/navigation/partials/_list-heading.html
  templates/navigation/partials/_list-item.html
  templates/navigation/partials/_preview-links.html
  templates/navigation/partials/_primary-links.html
  webapp/navigation.py
  yarn.lock
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#1341 Implement keyboard navigation
  static/js/navigation/elements.js
  static/js/navigation/keyboard-navigation.js
  static/js/navigation/main.js
  static/js/navigation/mobile.js
  static/js/navigation/search.js
  templates/base_index.html
  templates/navigation/navigation.html
  templates/navigation/partials/_dropdown-desktop.html
  templates/navigation/partials/_dropdown-mobile.html
  templates/navigation/partials/_list-heading.html
  templates/navigation/partials/_list-item.html
  templates/navigation/partials/_preview-links.html
  templates/navigation/partials/_primary-links.html
Labels: Review: Code +1, Review: QA +1

#1342 Implement GA tracking for the meganav
  static/js/navigation/ga-tracking.js
  static/js/navigation/main.js
  templates/navigation/navigation.html
Labels: Review: Code +1

#1344 feat: Only close the navigation when resizing horizontally
  static/js/navigation/main.js
  static/js/utils/throttle.js
Labels: Review: Code +1, Review: QA +1

#1340 WD-12247 Dev Create /data/mongodb/support
  templates/data/mongodb/support.html
  templates/data/sitemap.xml
Labels: Review: Code +1, Review: QA +1, Review: UX +1, Review: Design +1

#1345 chore: Update copy and images on /partners/executive-summit
  templates/partners/executive-summit.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#1349 chore: Update copy on /solutions/secure-open-source
  templates/solutions/secure-open-source/index.html
Labels: Review: Code +1, Review: QA +1

#1343 WD-12243 Dev Create data/mongodb/what-is-mongodb
  templates/data/mongodb/what-is-mongodb.html
  templates/data/sitemap.xml
Labels: Review: Code +1, Review: QA +1, Review: UX +1, Review: Design +1

#1347 bug: Replace homepage suru that was incompatible with firefox
  templates/index.html
Labels: Review: Code +1, Review: Design +1

#1348 feat: /data/mongodb revamp
  templates/data/mongodb.html
  templates/data/mongodb/index.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1, Review: Design +1

#1352 WD-12252 dev create /data/mongodb/managed
  templates/data/mongodb/managed.html
  templates/data/sitemap.xml
Labels: Review: Code +1, Review: QA +1, Review: UX +1, Review: Design +1

#1358 Update copy on careers FAQ page
  templates/careers/application/faq.html
Labels: Review: Code +1, Review: QA +1

#1359 update "four" to "4" in faq copy
  templates/careers/application/faq.html
Labels: Review: Code +1, Review: QA +1

#1355 Create MongoDB pages
  templates/data/mongodb.html
  templates/data/mongodb/index.html
  templates/data/mongodb/managed.html
  templates/data/mongodb/support.html
  templates/data/mongodb/what-is-mongodb.html
  templates/data/sitemap.xml
Labels: Review: QA +1
