Repository canonical/canonical.com, pull requests merged in 2024-02, with the labels that each got.

#1168 [WD-8454] update favicon for all browsers and devices
  static/files/site.webmanifest
  templates/base_index.html
Labels: Review: Code +1

#1171 WD-8618 - enable legal links on career forms
  templates/careers/job-detail.html
Labels: Review: QA +1, Review: UX +1, Review: Code +1 (with changes)

#1166 Improve code snippet as requested WD-7777
  static/sass/styles.scss
  templates/data/spark-on-kubernetes.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1 (with changes)

#1173 WD-8434 - update newsletter signup form on /blog
  templates/base_index.html
  templates/blog/article.html
  templates/blog/index.html
  templates/blog/newsletter-form.html
Labels: Review: QA +1, Review: UX +1, Review: Code +1 (with changes)

#1178 /contact-us copy update
  templates/contact-us.html
Labels: Review: Code +1, Review: QA +1

#1179 Copy update follow up /contact-us
  templates/contact-us.html
Labels: Review: Code +1, Review: QA +1

#1181 [WD-8953] serve favicon for search engines separately from local folder
  static/favicons/COF-favicon-48x48.png
  templates/base_index.html
Labels: Review: Code +1

#1182 Fix broken privacy link
  templates/lxd/_form-lxd-install.html
  templates/solutions/_form-big-data-ai.html
Labels: Review: Code +1, Review: QA +1

#1184 WD-8721 - create /solutions/infrastructure page
  templates/base_index.html
  templates/solutions/_form_infrastructure.html
  templates/solutions/infrastructure.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1, Review: Design +1

#1185 Copy update /data
  templates/data/index.html
Labels: Review: Code +1, Review: QA +1

#1190 Update issue templates
  .github/ISSUE_TEMPLATE/ISSUE_TEMPLATE.md
Labels: Review: Code +1 (with changes)
