Repository canonical/canonical.com, pull requests merged in 2024-05, with the labels that each got.

#1248 WD-10737 Remove microcloud roadmap page
  redirects.yaml
  templates/microcloud/roadshow.html
Labels: Review: Code +1, Review: QA +1

#1253 Remove roadmap navigation link
  templates/partial/_microcloud-navigation.html
Labels: Review: Code +1, Review: QA +1

#1255 Refresh /solutions/infrastructure page
  templates/solutions/infrastructure/index.html
Labels: Review: Code +1, Review: QA +1

#1256 Fix tabs on homepage not being scrollable
  static/sass/styles.scss
  templates/index.html
Labels: Review: Code needed, Review: QA +1

#1259 Remove sales contact numbers
  templates/contact-us.html
Labels: Review: Code +1, Review: QA +1

#1258 Inherit dark colours on homepage
  static/sass/styles.scss
  templates/index.html
Labels: Review: Code +1, Review: QA +1, Review: Design +1

#1261 Add is-muted to hr
  templates/index.html
Labels: Review: Code +1, Review: QA +1

#1260 Fix missing requisition ID
  tests/cassettes/TestApplicationPageHelpers.test_job_post_page.yaml
  tests/test_application.py
  webapp/app.py
Labels: Review: Code +1, Review: QA +1

#1262 djlint --reformat, fix elements nesting
  templates/careers/application/index.html
  templates/careers/application/partial/_early-stage.html
  templates/careers/application/partial/_late-stage.html
Labels: Review: Code +1, Review: QA +1
