Repository canonical/canonical.com, pull requests merged in 2024-07, with the labels that each got.

#1286 WD-12532 - add banner to c.com
  templates/index.html
Labels: Review: Code +1, Review: QA +1, Review: Design +1

#1288 WD-12940 - update canonicalwebteam.discourse to 5.6.1 and vanilla to …
  package.json
  requirements.txt
  yarn.lock
Labels: Review: QA +1

#1289 feat: Build secondary-navigation.yaml for dynamically building the secondary nav items
  secondary-navigation.yaml
Labels: Review: Code +1

#1284 WD-12107 Refreshed /lxd page
  templates/lxd/index.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#1294 refactor: Updates the reduced nav search to use newest Vanilla pattern
  package.json
  static/js/navigation.js
  templates/navigation/navigation.html
  templates/navigation/secondary-navigation.html
  yarn.lock
Labels: Review: QA +1, Review: Code +1 (with changes)

#1298 update candidate page expiration
  webapp/application.py
  webapp/utils/constants.py
Labels: Review: Code +1

#1293 WD-12299 Refreshed /solutions/secure-open-source
  templates/solutions/secure-open-source/index.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1, Review: Design +1

#1292 WD-12327 Refreshed /solutions/telco
  templates/solutions/telco/index.html
Labels: Review: QA +1, Review: UX +1, Review: Code +1 (with changes)

#1302 Update Dell logo
  templates/index.html
  templates/microcloud/index.html
Labels: Review: QA +1

#1303 WD-13399 Removed Duplicate Text
  templates/solutions/secure-open-source/index.html
Labels: Review: QA +1

#1307 Update URL path for /ai/infrastructure
  templates/solutions/ai/infrastructure/_form-ai-infrastructure.html
  templates/solutions/ai/infrastructure/index.html
Labels: Review: QA +1

#1309 Remove chevron custom stylings
  static/sass/_pattern_careers-progression.scss
  static/sass/styles.scss
Labels: Review: QA +1

#1306 Build /ai/edge page
  templates/solutions/ai/edge.html
Labels: Review: QA +1, Review: UX +1, Review: Design +1, Review: Code +1 (with changes)

#1312 WD-13517 Copy Update Text
  templates/solutions/secure-open-source/index.html
Labels: Review: Code +1, Review: QA +1

#1313 Remove defunct link in issue template
  .github/ISSUE_TEMPLATE/ISSUE_TEMPLATE.md
Labels: Review: Code +1

#1308 WD-12223 Refreshed /data/opensearch
  templates/data/opensearch.html
  templates/data/opensearch/index.html
Labels: Review: QA +1, Review: UX +1, Review: Design +1, Review: Code +1 (with changes)

#1311 WD-12230 Created /data/opensearch/what-is-opensearch
  templates/data/opensearch/what-is-opensearch.html
  templates/data/sitemap.xml
Labels: Review: Code +1, Review: QA +1, Review: UX +1, Review: Design +1

#1319 WD-13331 Updated contact-us page
  templates/contact-us.html
Labels: Review: Code +1, Review: QA +1

#1317 [WD-12238] new webpage at /data/opensearch/managed
  Dockerfile
  templates/data/_form-data-opensearch.html
  templates/data/opensearch/index.html
  templates/data/opensearch/managed.html
Labels: Review: QA +1, Review: UX +1, Review: Design +1, Review: Code +1 (with changes)

#1314 Build /solutions/ubuntu-os and modal form
  templates/solutions/ubuntu-os/_form-ubuntu-os.html
  templates/solutions/ubuntu-os/index.html
Labels: Review: QA +1, Review: UX +1, Review: Design +1, Review: Code +1 (with changes)
