Repository canonical/canonical.com, pull requests merged in 2025-09, with the labels that each got.

#1926 [WD-26363] chore: use Divided section pattern
  templates/openstack/compare/index.html
Labels: Review: Code +1, Review: QA +1

#1929 feat: Update copy on /open-source-security
  templates/solutions/open-source-security/index.html
Labels: Review: Code +1, Review: QA +1

#1922 Feat: Updated navigation for /mlops
  secondary-navigation.yaml
Labels: Review: QA +1

#1925 WD-23682 - Refresh canonical.com/mlops
  package.json
  postcss.config.js
  secondary-navigation.yaml
  templates/macros/_vf_resources.jinja
  templates/mlops/index.html
  yarn.lock
Labels: Review: QA +1, Review: UX +1, Review: Design +1, Review: Code +1 (with changes)

#1934 fix: ubuntu pro link
  templates/legal/ubuntu-pro/index.md
Labels: Review: Code +1, Review: QA +1

#1946 [WD-26911] fix: failing newsletter form
  templates/openstack/resources.html
Labels: Review: Code +1, Review: QA +1

#1948 Update Big data analytics to MLOps
  redirects.yaml
  secondary-navigation.yaml
Labels: Review: Code +1, Review: QA +1

#1957 fix(projects): remove aether project [WD-26978]
  templates/projects/index.html
Labels: Review: Code +1, Review: QA +1

#1955 Update logic for bubble nav to match exact child path
  webapp/navigation.py
Labels: Review: Code +1, Review: QA +1

#1954 WD-26377: [Case Study] Machine learning for financial services
  templates/case-study/machine-learning-for-financial-services.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1, Review: Design +1

#1939 [WD-26370] Add canonical.com/data/warehouse
  templates/data/sitemap.xml
  templates/data/warehouse/index.html
Labels: Review: QA +1, Review: UX +1, Review: Design +1, Review: Code +1 (with changes)

#1936 [WD-26492] Update canonical.com/data-and-ai copydoc
  secondary-navigation.yaml
  templates/solutions/data-and-ai/index.html
Labels: Don't merge, Review: Code +1, Review: QA +1

#1966 WD-27219 Update Nova case study
  templates/case-study/nova-telecommunications.html
Labels: Review: Code +1, Review: QA +1

#1970 Fix typo in footer HTML
  templates/partial/_footer.html
Labels: Review: Code +1

#1973 WD-27608: `/data/spark/what-is-spark` copy updates
  templates/data/spark/what-is-spark.html
Labels: Review: Code needed, Review: QA needed

#1976 copy update: /data/kafka
  templates/data/kafka/index.html
Labels: Review: Code +1, Review: QA +1
