Repository canonical/canonical.com, pull requests merged in 2025-06, with the labels that each got.

#1726 Update contact us
  templates/contact-us.html
Labels: Review: Code +1, Review: QA +1

#1723 Migrate and rebrand /solutions/financial-services
  navigation.yaml
  secondary-navigation.yaml
  static/js/tabbed-content.js
  static/sass/styles.scss
  templates/careers/hiring-process/index.html
  templates/consulting/index.html
  templates/macros/_vf_tiered-list.jinja
  templates/navigation/secondary-navigation.html
  templates/shared/_blog-card.html
  templates/solutions/financial-services/form-data.json
  templates/solutions/financial-services/index.html
  templates/solutions/index.html
  templates/solutions/telco/index.html
  webapp/navigation.py
Labels: Review: QA +1, Review: UX +1, Review: Design +1, Review: Code +1 (with changes)

#1731 Add new page data/spark/managed
  secondary-navigation.yaml
  templates/data/spark/managed.html
Labels: Review: Code +1, Review: QA +1

#1738 WD-22237: Created solutions/data-and-ai webpage
  secondary-navigation.yaml
  templates/solutions/data-and-ai/form-data.json
  templates/solutions/data-and-ai/index.html
  templates/solutions/index.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1, Review: Design +1

#1730 feat: case study nova telecommunications
  templates/case-study/nova-telecommunications.html
Labels: Review: QA +1, Review: UX +1, Review: Design +1, Review: Code +1 (with changes), Review: PdM +1

#1724 Automotive landing page
  navigation.yaml
  secondary-navigation.yaml
  static/sass/styles.scss
  templates/solutions/automotive/form-data.json
  templates/solutions/automotive/index.html
  templates/solutions/index.html
Labels: Review: QA +1, Review: UX +1, Review: Design +1, Review: Code +1 (with changes)

#1751 page refresh: /projects
  navigation.yaml
  templates/projects/index.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1, Review: Design +1

#1752 Refresh /careers/company-culture/progression
  static/sass/_pattern_careers-progression.scss
  templates/careers/company-culture/progression.html
  templates/macros/_macro-lite-video.jinja
Labels: Review: Code +1, Review: QA +1, Review: Design +1

#1749 Migration: Buyer's guide engage page from u.com
  templates/solutions/automotive/buyers-guide/_form.html
  templates/solutions/automotive/buyers-guide/index.html
Labels: Review: Code +1, Review: QA +1

#1761 Copy update: c.com/solutions/ubuntu-os/workstations
  templates/solutions/ubuntu-os/workstations.html
Labels: Review: Code +1, Review: QA +1

#1758 chore: remove Cypress and related test files from project dependencies
  package.json
  tests/cypress/cypress.json
  tests/cypress/integration/sample_spec.js
  tests/cypress/plugins/index.js
  tests/cypress/support/commands.js
  tests/cypress/support/index.js
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#1765 feat: Rebrand search page
  requirements.txt
  templates/search.html
  webapp/app.py
Labels: Review: Code +1, Review: QA +1

#1766 [copy update] WD-23242 - Update on /solutions/data-and-ai
  templates/solutions/data-and-ai/index.html
Labels: Review: Code +1, Review: QA +1
