Repository canonical/canonical.com, pull requests merged in 2025-01, with the labels that each got.

#1481 [WD-17929] Copy update on data/kafka/what-is-kafka
  templates/data/kafka/what-is-kafka.html
Labels: Review: Code +1, Review: QA +1

#1462 WD-17652 Copy update on the /solutions/telco/5g-edge page
  templates/solutions/telco/5g-edge.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#1456 [WD-17199] job apply recaptcha
  .env
  konf/site.yaml
  requirements.txt
  templates/base_index.html
  templates/careers/job-detail.html
  tests/test_recaptcha.py
  webapp/app.py
  webapp/greenhouse.py
  webapp/recaptcha.py
Labels: Review: Code +1, Review: QA +1

#1482 Update what is mongodb page
  templates/data/mongodb/what-is-mongodb.html
Labels: Review: Code +1, Review: QA +1, Maintenance 🔨

#1486 check canonicaljobs board as well for directly accessed job post
  webapp/greenhouse.py
Labels: Review: Code +1, Review: QA +1

#1483 WD-17945 Copy updates [canonical.com/solutions/telco]
  templates/solutions/telco/index.html
Labels: Review: Code +1, Review: QA +1

#1474 [WD-17951] use different footer for docs pages
  templates/base_index.html
  templates/docs/shared/_docs.html
  templates/docs/shared/_footer.html
Labels: Review: Code +1, Review: QA +1

#1455 Page refresh: /solutions/ai
  templates/solutions/ai/index.html
Labels: Review: QA +1, Review: UX +1, Review: Design +1, Review: Code +1 (with changes)

#1488 WD-17296-dev-create-solutions-open-source-security-cyber-resilience-act
  static/files/forms-data.json
  templates/solutions/open-source-security/cyber-resilience-act/index.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#1495 fix(open-source-security): EU Cyber Resilience Act updates [WD-18099]
  templates/solutions/open-source-security/index.html
Labels: Review: Code +1, Review: QA +1

#1496 Add anchor id to company values
  templates/company/index.html
Labels: Review: Code +1, Review: QA +1

#1489 Migrate '/download/iot/intel-iot#get-in-touch' form to c.com
  requirements.txt
  static/files/forms-data.json
  static/js/careers-filter-and-sort.js
  static/js/forms.js
  static/js/modals.js
  static/js/osselector.js
  static/js/prepare-form-inputs.js
  static/js/tabbed-content.js
  static/sass/_pattern_forms.scss
  templates/data/postgresql/form-data.json
  templates/partners/silicon/intel/form-data.json
  templates/partners/silicon/intel/index.html
  templates/shared/forms/form-fields.html
  templates/shared/forms/form-template.html
  templates/solutions/open-source-security/cyber-resilience-act/form-data.json
  templates/solutions/telco/form-data.json
  webapp/app.py
Labels: Review: QA +1, Review: Code +1 (with changes)

#1502 fix: removed repeat linebreak
  templates/blog/featured-articles.html
Labels: Review: Code +1, Review: QA +1

#1501 RECAPTCHA_ENABLED="true"
  konf/site.yaml
Labels: Review: Code +1

#1507 fix(/blog/article): Disable djlint for json data processing
  templates/blog/article.html
Labels: Review: Code +1

#1505 Copy update on /solutions/open-source-security/cyber-resilience-act
  templates/solutions/open-source-security/cyber-resilience-act/index.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#1511 fix: render close button above all input elements
  static/sass/styles.scss
Labels: Review: Code +1, Review: QA +1

#1510 Update partner logos on solutions/ai page
  templates/solutions/ai/index.html
Labels: Review: Code needed, Review: QA needed

#1508 feat: Move case studies and macros from u.com
  templates/case-study/_case-study-card.html
  templates/case-study/_case-study-modal.html
  templates/case-study/base_case-study.html
  templates/case-study/esa.html
  templates/case-study/grundium-ubuntu-pro-for-devices.html
  templates/case-study/index.html
  templates/case-study/lucid-aws-fedramp-compliance-case-study.html
  templates/case-study/sbi-bits.html
  templates/case-study/ubuntu-pro-support-for-games-developer.html
  templates/macros/_macros-cta.jinja
  templates/macros/_macros-highlights.jinja
  templates/macros/_macros-image.jinja
  templates/macros/_macros-text-list.jinja
  templates/macros/_macros-text.jinja
  templates/solutions/open-source-security/cyber-resilience-act/index.html
Labels: Review: Code +1, Review: QA +1

#1512 fix: push correct origin for button events
  static/js/navigation/ga-tracking.js
Labels: Review: Code +1, Review: QA +1

#1509 feat: Build case study index page
  konf/site.yaml
  requirements.txt
  static/sass/_pattern_blog-card.scss
  static/sass/_pattern_strip.scss
  static/sass/styles.scss
  templates/case-study/index.html
  webapp/app.py
Labels: Review: Code +1, Review: QA +1

#1518 Fix: Correct Meta_description for wordpress Blogs
  requirements.txt
  templates/blog/article.html
Labels: Review: Code +1, Review: QA +1

#1517 Update meganav to US spelling
  navigation.yaml
Labels: Review: Code +1, Review: QA +1

#1506 fix(candidate): Remove the bespoke styling: detailed stepped list
  static/sass/styles.scss
Labels: Review: Code needed, Review: QA needed

#1520 feat: Apply design requests on case study macros
  templates/case-study/esa.html
  templates/macros/_macros-highlights.jinja
  templates/macros/_macros-image.jinja
  templates/macros/_macros-text-list.jinja
  templates/macros/quote_wrapper.jinja
  templates/microcloud/index.html
  templates/solutions/ai/index.html
  templates/solutions/telco/5g-core.html
  templates/solutions/telco/5g-edge.html
Labels: Review: Design needed, Review: Code +1, Review: QA +1

#1525 upgrade flask-base to enable assets compression
  requirements.txt
  templates/base_index.html
  templates/index.html
  templates/navigation/partials/_preview-links.html
Labels: Review: Code +1, Review: QA +1

#1526 fix: remove `p-block` throughout partners bubble
  templates/partners/become-a-partner.html
  templates/partners/channel-and-reseller.html
  templates/partners/desktop.html
  templates/partners/executive-summit.html
  templates/partners/find-a-partner.html
  templates/partners/gsi.html
  templates/partners/ihv-and-oem.html
  templates/partners/iot-device.html
  templates/partners/isv-partners.html
  templates/partners/public-cloud.html
  templates/partners/silicon/index.html
Labels: Review: Code +1, Review: QA +1

#1527 fix: /lxd/manage modal
  templates/lxd/manage.html
Labels: Review: Code +1, Review: QA +1

#1524 [WD-18429] Migrated /embedding from u.com to c.com
  package.json
  templates/embedding/faqs.html
  templates/embedding/form-data.json
  templates/embedding/index.html
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#1523 fix: Remove `p-block` usage
  templates/blog/article.html
  templates/blog/blog-card.html
  templates/careers/_base-department.html
  templates/careers/company-culture/remote-work.html
  templates/careers/index.html
  templates/contact-us.html
  templates/documentation/_documentation-header.html
  templates/documentation/beyond-canonical.html
  templates/documentation/index.html
  templates/documentation/open-documentation-academy.html
  templates/documentation/work-and-careers.html
  templates/partial/_careers_navigation.html
Labels: Review: Code +1, Review: QA +1

#1522 feat: Add language filter function for case studies
  requirements.txt
  templates/case-study/esa.html
  templates/case-study/grundium-ubuntu-pro-for-devices.html
  templates/case-study/index.html
  templates/case-study/lucid-aws-fedramp-compliance-case-study.html
  templates/case-study/sbi-bits.html
  templates/case-study/ubuntu-pro-support-for-games-developer.html
  webapp/app.py
Labels: Review: Code +1, Review: QA +1

#1532 [WD-16811] Made top nav sticky like on u.com
  static/sass/_pattern_navigation.scss
Labels: Review: Code +1, Review: QA +1

#1521 Add links to certified devices on Intel partner page
  templates/partners/silicon/intel/index.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#1494 copy: create /solutions/iot-and-devices page. WD-17347
  navigation.yaml
  templates/solutions/iot-and-devices/form-data.json
  templates/solutions/iot-and-devices/index.html
Labels: Review: QA +1, Review: UX +1, Review: Design +1, Review: Code +1 (with changes)

#1529 Wd 8834 fix: full width tabbed list on medium screens + fixed side navigation
  static/sass/styles.scss
  templates/documentation/_documentation-tab-navigation.html
Labels: Review: Code +1, Review: QA +1

#1519 Case study migration
  konf/site.yaml
  requirements.txt
  static/sass/_pattern_blog-card.scss
  static/sass/_pattern_strip.scss
  static/sass/styles.scss
  templates/case-study/_case-study-card.html
  templates/case-study/_case-study-modal.html
  templates/case-study/base_case-study.html
  templates/case-study/esa.html
  templates/case-study/grundium-ubuntu-pro-for-devices.html
  templates/case-study/index.html
  templates/case-study/lucid-aws-fedramp-compliance-case-study.html
  templates/case-study/sbi-bits.html
  templates/case-study/ubuntu-pro-support-for-games-developer.html
  templates/macros/_macros-cta.jinja
  templates/macros/_macros-highlights.jinja
  templates/macros/_macros-image.jinja
  templates/macros/_macros-text-list.jinja
  templates/macros/_macros-text.jinja
  templates/macros/quote_wrapper.jinja
  templates/microcloud/index.html
  templates/solutions/ai/index.html
  templates/solutions/telco/5g-core.html
  templates/solutions/telco/5g-edge.html
  webapp/app.py
Labels: Review: QA +1, Review: Code +1 (with changes)

#1536 [WD-18726] Introduced an optional formId prop to form-template.html
  templates/embedding/index.html
  templates/shared/forms/form-fields.html
  templates/shared/forms/form-template.html
Labels: Review: Code +1, Review: QA +1

#1535 fix: remove final `p-block` instances
  templates/press-centre/card.html
  templates/press-centre/index.html
  templates/projects/directory.html
  templates/projects/index.html
  templates/shared/_promoted_roles.html
Labels: Review: Code +1, Review: QA +1

#1533 WD-18237 Migrate /observability bubble to Canonical.com
  secondary-navigation.yaml
  static/js/modals.js
  static/sass/styles.scss
  templates/observability/_managed-observability-modal.html
  templates/observability/_observability-modal.html
  templates/observability/contact-us.html
  templates/observability/index.html
  templates/observability/managed.html
  templates/observability/what-is-observability.html
  templates/shared/_blog-card.html
  templates/shared/_client-contact-us-form.html
Labels: Review: QA +1, Review: Code +1 (with changes)
