Repository canonical/canonical.com, pull requests merged in 2025-03, with the labels that each got.

#1584 refactor: Migrate openstack form to use form generator
  templates/openstack/_form-openstack.html
  templates/openstack/form-data.json
  templates/openstack/index.html
Labels: Review: Code +1, Review: QA +1

#1580 update headcount
  templates/careers/company-culture/index.html
Labels: Review: Code +1

#1579 US spelling change
  templates/index.html
Labels: Review: Code +1

#1586 copy: update /case-study/esa. WD-19769
  templates/case-study/esa.html
Labels: Review: QA +1

#1577 Build page on /solutions/cloud-native-development
  package.json
  static/js/modals.js
  templates/solutions/cloud-native-development/form-data.json
  templates/solutions/cloud-native-development/index.html
  yarn.lock
Labels: Review: Code +1, Review: QA +1, Review: UX +1, Review: Design +1

#1591 feat: Implement sitemaps tree parser
  requirements.txt
  templates/data/docs/index.html
  webapp/app.py
Labels: Review: Code +1, Review: QA +1

#1581 Wd 19673 please help to update beijing shanghai office new address in canonical website thanks https canonical com contact us
  templates/contact-us.html
Labels: Review: Code +1, Review: QA +1

#1587 Replace image with diagram on /solutions/iot-and-devices
  templates/solutions/iot-and-devices/index.html
Labels: Review: Code +1, Review: QA +1, Review: Design +1

#1594 chore: Update content on /solutions/infrastructure
  templates/solutions/infrastructure/index.html
Labels: Review: Code +1, Review: QA +1

#1595 fix: Hot fix for careers 500ing due to missing department field
  webapp/greenhouse.py
Labels: Review: Code +1, Review: QA +1

#1588 feat: Add 'Allainces' to careers section
  navigation.yaml
  static/sass/styles.scss
  templates/careers/_base-department.html
  templates/careers/alliances.html
  templates/careers/includes/_alliances-blog.html
  templates/careers/includes/_alliances-intro.html
  templates/careers/includes/_fast-track-jobs.html
  templates/careers/index.html
  templates/partial/_careers_navigation.html
  webapp/app.py
  webapp/greenhouse.py
Labels: Review: Code +1, Review: QA +1, Review: UX +1, Review: Design +1

#1593 feat: Update requirements to use sitemaps-parser package
  requirements.txt
  webapp/app.py
Labels: Review: Code +1, Review: QA +1

#1598 chore: Bump vanilla version
  package.json
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#1602 update broken charmhub.io link
  templates/data/postgresql/index.html
Labels: Review: Code needed, Review: QA needed

#1603 [WD-20171] fix: Global nav and tabbed content glitches
  static/js/navigation/main.js
  templates/index.html
  templates/navigation/partials/_dropdown-desktop.html
  templates/navigation/partials/_tab-panel.html
Labels: Review: Code +1, Review: QA +1

#1601 feat: Build sitemaps template with directory parser
  Dockerfile
  requirements.txt
  static/files/sitemap_tree.xml
  templates/sitemap_children.xml
  templates/sitemap_template.xml
  webapp/app.py
Labels: Review: QA +1, Review: Code +1 (with changes)

#1609 unflip single-select options in job application
  templates/careers/job-detail.html
Labels: Review: Code +1, Review: QA +1

#1611 feat: copy update
  templates/solutions/iot-and-devices/index.html
Labels: Review: Code +1, Review: QA +1

#1599 Add CTA section to bottom of page
  templates/solutions/open-source-security/cyber-resilience-act/index.html
Labels: Review: QA +1, Review: UX +1, Review: Code +1 (with changes)

#1607 chore: Use git diff to get changed files
  .github/workflows/pr.yaml
Labels: Review: Code +1, Review: QA +1

#1615 Update hiring process information
  templates/careers/application/index.html
  templates/careers/hiring-process/index.html
Labels: Review: Code +1, Review: QA +1

#1608 Changed url to new summit page
  navigation.yaml
Labels: Review: Code +1, Review: QA +1

#1612 Wd 19232 dev web page refresh update microcloud resources
  static/js/microcloud-slider.js
  static/sass/styles.scss
  templates/microcloud/resources.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1, Review: Design +1

#1617 Small link change on microcloud resources
  templates/microcloud/resources.html
Labels: Review: Code needed, Review: QA needed, Priority: Critical, Released ✈️

#1618 feat: Add 'tag' filter to /case-study search
  requirements.txt
  templates/case-study/index.html
  webapp/app.py
Labels: Review: QA +1, Review: Code +1 (with changes)

#1619 fix: Update link to privacy policy on /embedding/faqs
  templates/embedding/faqs.html
Labels: Review: Code +1, Review: QA +1
