Repository canonical/canonical.com, pull requests merged in 2025-08, with the labels that each got.

#1830 Update Graduate job post link
  templates/careers/includes/_fast-track-jobs.html
Labels: Review: Code +1, Review: QA +1

#1832 Update secondary-navigation.yaml
  secondary-navigation.yaml
Labels: Review: Code +1, Review: QA +1

#1836 feat: add bubble nav to /data/valkey
  secondary-navigation.yaml
Labels: Review: Code +1, Review: QA +1

#1825 Change image loading from 'auto|lazy' to 'lazy' for consistency
  templates/case-study/lucid-aws-fedramp-compliance-case-study.html
  templates/case-study/ubuntu-pro-support-for-games-developer.html
  templates/consulting/index.html
  templates/data/kafka/index.html
  templates/data/valkey/what-is-valkey.html
  templates/edge-computing/index.html
  templates/openstack/index.html
  templates/solutions/data-and-ai/index.html
  templates/solutions/industrial/index.html
  templates/solutions/telco/index.html
  templates/solutions/telco/open-ran.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#1824 Set up redirects and remove stale docs logic
  redirects.yaml
  templates/data/docs/kafka/iaas/document.html
  templates/data/docs/kafka/iaas/search-results.html
  templates/data/docs/kafka/k8s/document.html
  templates/data/docs/kafka/k8s/search-results.html
  webapp/app.py
Labels: Review: Code +1, Review: QA +1

#1846 feat: add /mlops/feast to secondary nav
  secondary-navigation.yaml
Labels: Review: Code +1, Review: QA +1

#1843 WD-24528: Add ESA video to the public sector page
  templates/public-sector/index.html
Labels: Review: Code +1, Review: QA +1

#1818 feat: created charmed kubeflow index page
  navigation.yaml
  package.json
  secondary-navigation.yaml
  templates/data/kafka/support.html
  templates/data/mongodb/support.html
  templates/data/mysql/support.html
  templates/data/opensearch/support.html
  templates/data/postgresql/support.html
  templates/data/spark/support.html
  templates/data/valkey/index.html
  templates/mlops/kubeflow/index.html
  templates/solutions/ai/big-data-ai/index.html
  templates/solutions/ai/index.html
  templates/solutions/telco/5g-edge.html
  templates/solutions/telco/open-ran.html
  yarn.lock
Labels: Review: Code +1, Review: QA +1, Review: UX +1, Review: Design +1

#1859 style: hide duplicated hr rule on /spark/support page
  templates/data/spark/support.html
Labels: Review: Code +1, Review: QA +1

#1844 [WD-23821] feat: Migrate mlflow, mlops-workshop pages to canonical.com/mlops
  navigation.yaml
  static/sass/styles.scss
  templates/data/kafka/support.html
  templates/data/mongodb/support.html
  templates/data/mysql/support.html
  templates/data/opensearch/support.html
  templates/data/postgresql/support.html
  templates/data/spark/support.html
  templates/data/valkey/index.html
  templates/mlops/contact-us.html
  templates/mlops/feast.html
  templates/mlops/feast/form-data.json
  templates/mlops/form-data.json
  templates/mlops/mlflow.html
  templates/mlops/mlops-workshop.html
  templates/solutions/ai/big-data-ai/index.html
  templates/solutions/ai/index.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#1860 Fix missing cover image aspect ratios
  templates/observability/what-is-observability.html
  templates/solutions/ai/index.html
Labels: Review: Code +1, Review: QA +1, Bug 🐛

#1857 chore: Migrate /mlops/kubeflow/what-is-kubeflow
  secondary-navigation.yaml
  templates/mlops/kubeflow/what-is-kubeflow.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#1861 update footer
  static/js/cookie-policy-with-callback.js
  static/js/tabbed-content.js
  static/sass/_maas_styles.scss
  static/sass/_pattern_lists.scss
  static/sass/_pattern_navigation.scss
  static/sass/_pattern_venobox.scss
  templates/partial/_footer.html
Labels: Review: Code +1, Review: QA +1, Review: Design +1

#1865 WD-24630: Updated link
  templates/solutions/index.html
Labels: Review: QA +1

#1867 style(footer): update footer styling with dark theme class
  templates/partial/_footer.html
Labels: Review: Code +1, Review: QA +1, Review: Design +1

#1864 fix: MAAS tutorials server error
  navigation.yaml
  templates/consulting/index.html
  templates/lxd/index.html
  templates/lxd/manage.html
  templates/openstack/architecture.html
  templates/projects/index.html
  templates/solutions/infrastructure/sovereign-cloud.html
  templates/solutions/telco/tabs/_telco-bare-metal-tab.html
  webapp/app.py
Labels: Review: Code +1, Review: QA +1

#1811 feat: migrate Canonical CLA form from ubuntu.com
  .env
  build.js
  charm/charmcraft.yaml
  konf/site.yaml
  package.json
  requirements.txt
  static/js/canonical-cla/README.md
  static/js/canonical-cla/app.tsx
  static/js/canonical-cla/components/AgreementTypeForm/IndividualCla.tsx
  static/js/canonical-cla/components/AgreementTypeForm/OrganizationCla.tsx
  static/js/canonical-cla/components/AgreementTypeForm/index.tsx
  static/js/canonical-cla/components/ContactDetailsForm/IndividualContactForm.tsx
  static/js/canonical-cla/components/ContactDetailsForm/OrganizationContactForm.tsx
  static/js/canonical-cla/components/ContactDetailsForm/index.tsx
  static/js/canonical-cla/components/GithubEmailSelector.tsx
  static/js/canonical-cla/components/LaunchpadEmailSelector.tsx
  static/js/canonical-cla/components/ScrollToHashElement.tsx
  static/js/canonical-cla/contexts/SignForm.tsx
  static/js/canonical-cla/hooks/usePersistedForm.ts
  static/js/canonical-cla/pages/SignPage.tsx
  static/js/canonical-cla/pages/SuccessPage.tsx
  static/js/canonical-cla/utils/address.ts
  static/js/canonical-cla/utils/api.ts
  static/js/canonical-cla/utils/constants.ts
  static/sass/_pattern_icons.scss
  static/sass/styles.scss
  templates/legal/contributors/agreement.html
  tests/cla/__init__.py
  tests/cla/test_routes.py
  tsconfig.json
  webapp/app.py
  webapp/canonical_cla/views.py
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#1842 feat: migrate mlops index page
  navigation.yaml
  secondary-navigation.yaml
  templates/mlops/contact-us.html
  templates/mlops/form-data.json
  templates/mlops/index.html
  templates/partners/silicon/intel/index.html
  templates/shared/_azure-banner.html
  templates/solutions/ai/index.html
  templates/solutions/ai/infrastructure/index.html
  templates/solutions/data-and-ai/index.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#1873 Copy update: Careers application FAQ content refresh
  templates/careers/application/faq.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#1874 Replace Written Interview with assessment
  templates/careers/application/faq.html
Labels: Review: Code +1

#1880 copy update: open source security
  templates/solutions/open-source-security/index.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#1889 feat(WD-25572): anbox-cloud - contact form - make comment field required
  templates/anbox-cloud/form-data.json
Labels: Review: Code +1, Review: QA +1

#1892 feat(/case-study): Order tags alphabetically
  webapp/app.py
Labels: Review: Code needed, Review: QA needed

#1885 use image template on /data and /documentation pages
  templates/data/mysql/managed.html
  templates/data/opensearch/managed.html
  templates/data/postgresql/what-is-postgresql.html
  templates/data/spark/support.html
  templates/documentation/beyond-canonical.html
  templates/documentation/work-and-careers.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#1888 chore: assets updated to use image template
  templates/partners/desktop.html
  templates/partners/executive-summit.html
  templates/partners/thank-you.html
  templates/press-centre/index.html
  templates/public-sector/index.html
  templates/solutions/ai/genai.html
  templates/solutions/automation/index.html
  templates/solutions/iot-and-devices/index.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#1893 feat: Add meta image to /mlops/kubeflow
  templates/mlops/kubeflow/index.html
Labels: Review: Code +1, Review: QA +1

#1851 feat: Migrate jaas.ai to c.com/jaas
  navigation.yaml
  redirects.yaml
  secondary-navigation.yaml
  static/js/tabbed-content.js
  static/sass/_pattern_forms.scss
  static/sass/styles.scss
  templates/dqlite/index.html
  templates/jaas/form-data.json
  templates/jaas/index.html
  templates/mir/index.html
  templates/observability/what-is-observability.html
  webapp/app.py
Labels: Review: QA +1, Review: Code +1 (with changes)

#1899 refactor(CLA Form): Remove phone number field from Individual form
  static/js/canonical-cla/components/ContactDetailsForm/IndividualContactForm.tsx
  static/js/canonical-cla/utils/constants.ts
Labels: Review: Code needed

#1897 chore: Bump Vanilla to 4.30.0
  package.json
  yarn.lock
Labels: Review: QA needed

#1906 [WD-26050] remove a section from /mlops page
  templates/mlops/index.html
Labels: Review: QA +1

#1904 update graduate job link
  templates/careers/includes/_fast-track-jobs.html
Labels: Review: QA +1

#1905 Bugfix: added acquisition url field
  templates/maas/contact-us.html
Labels: Review: Code +1, Review: QA +1

#1902 fix: Adjust image sizes on /solutions/automation
  templates/solutions/automation/index.html
Labels: Review: Code +1, Review: QA +1

#1868 feat: create open source adoption page
  navigation.yaml
  templates/open-source-adoption/index.html
Labels: Don't merge, Review: Code +1, Review: QA +1, Review: UX +1, Review: Design +1

#1908 [WD-25054] feat: added secondary navigation on /legal bubble
  secondary-navigation.yaml
Labels: Review: QA +1

#1914 Update withdrawal reasons
  webapp/application.py
Labels: Review: Code +1, Review: QA +1

#1910 Bugfix: added updated link to privacy policy
  templates/data/_form-data-kafka.html
  templates/data/_form-data-mongodb.html
  templates/data/_form-data-opensearch.html
  templates/data/_form-data-relational-dbs.html
  templates/data/_form-data-spark.html
  templates/data/_form-data-valkey.html
  templates/legal/terms-and-policies/snap-store-terms.md
  templates/legal/ubuntu-pro/personal/index.md
  templates/maas/contact-us.html
Labels: Review: Code +1, Review: QA +1

#1911 chore: update latest-news package, lazyload below fold images
  build.js
  package.json
  static/js/homepage/animations.js
  static/js/homepage/center-animations.js
  templates/index.html
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#1919 Feat: Added redirect for blog tag
  redirects.yaml
Labels: Review: QA +1

#1918 feat(CLA): Add organisation form new fields
  static/js/canonical-cla/components/ContactDetailsForm/OrganizationContactForm.tsx
  static/js/canonical-cla/utils/constants.ts
Labels: Review: Code +1, Review: QA +1
