Repository canonical/canonical.com, pull requests merged in 2025-10, with the labels that each got.

#1972 WD-27346: `/solutions/industrial` copy updates
  templates/solutions/industrial/index.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1, Review: Design +1

#1947 Feature juju rebrand and migration
  navigation.yaml
  redirects.yaml
  requirements.txt
  secondary-navigation.yaml
  static/sass/styles.scss
  templates/juju/charmhub-community.html
  templates/juju/charms-architecture.html
  templates/juju/docs/index.html
  templates/juju/docs/search.html
  templates/juju/form-data.json
  templates/juju/how-juju-works.html
  templates/juju/index.html
  templates/juju/integrations.html
  templates/juju/juju-architecture.html
  templates/juju/model-driven-operations-manifesto.html
  templates/juju/partials/_contact-us.html
  templates/juju/why-juju.html
  templates/maas/docs/base_docs.html
  webapp/app.py
  webapp/utils/juju_doc_search.py
Labels: Don't merge, Review: QA +1

#1982 feat: add /juju/latest.json endpoint
  README.md
  requirements.txt
  webapp/app.py
Labels: Review: QA +1, Review: Code +1 (with changes)

#1981 refactor: /data/kafka page to use vanilla patterns
  templates/data/kafka/index.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#1988 docs: add spark k8s docs redirect
  redirects.yaml
Labels: Review: Code +1, Review: QA +1

#1990 Fix: updated failing links
  navigation.yaml
  redirects.yaml
  secondary-navigation.yaml
  templates/blog/article.html
  templates/jaas/index.html
  templates/legal/websites.md
  templates/lxd/manage.html
  templates/maas/index.html
  templates/mlops/feast.html
  templates/mlops/mlflow.html
  templates/observability/managed.html
  templates/openstack/architecture.html
  templates/projects/index.html
  templates/solutions/automation/index.html
  templates/solutions/index.html
  templates/solutions/telco/5g-edge.html
  templates/solutions/telco/tabs/_telco-apps-infra-tab.html
  webapp/app.py
  webapp/static_data.py
Labels: Review: Code +1, Review: QA +1

#1989 update graduate job link
  templates/careers/includes/_fast-track-jobs.html
Labels: Review: QA +1

#1992 WD-29304 (remove "cloud native operations report" from meganav)
  navigation.yaml
Labels: Review: Code +1, Review: QA +1
