Repository canonical/canonical.com, pull requests merged in 2025-02, with the labels that each got.

#1538 feat: Add 'selfReportedAttribution' field to 3 high traffic forms for testing
  templates/partners/partial/_homepage-form.html
  templates/solutions/infrastructure/_form_infrastructure.html
  templates/solutions/open-source-security/_form-open-source-security.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#1540 feat: Add /observability to the meganav
  navigation.yaml
Labels: Review: Code +1, Review: QA +1

#1487 add MySQL support page
  secondary-navigation.yaml
  templates/data/mysql/support.html
Labels: Review: QA +1, Review: UX +1, Review: Design +1, Review: Code +1 (with changes)

#1544 fix: Fix typo on /solutions/iot-and-devices
  templates/solutions/iot-and-devices/index.html
Labels: Review: Code +1, Review: QA +1

#1542 Add episensor case study
  templates/case-study/episensor.html
  templates/macros/_macros-quote-wrapper.jinja
Labels: Review: QA +1, Review: Design +1, Review: Code +1 (with changes)

#1552 fix(meganav): ensure nav remains sticky with menu open
  static/sass/_pattern_navigation.scss
  static/sass/_pattern_strip.scss
  static/sass/styles.scss
Labels: Review: Code +1, Review: QA +1

#1553 fix(navigation): Remove 'Streaming' link from /data [WD-19130]
  secondary-navigation.yaml
Labels: Review: QA +1

#1543 feat: remove /projects/directory page
  redirects.yaml
  static/sass/styles.scss
  templates/projects/directory.html
  templates/projects/index.html
  templates/sitemap-links.xml
Labels: Review: Code +1, Review: QA +1

#1557 Add Airlock Digital case study
  templates/case-study/airlock-digital-ubuntu-pro-azure-case-study.html
Labels: Review: Code +1, Review: QA +1, Review: Design +1

#1558 [WD-19324] Copy Update - Airlock case study
  templates/case-study/airlock-digital-ubuntu-pro-azure-case-study.html
Labels: Review: Code +1

#1559 Update How We Hire video on Candidate Dashboard
  templates/careers/application/index.html
Labels: Review: Code +1, Review: QA +1

#1555 feat: Add discourse url metatag for case studies
  templates/base_index.html
  templates/case-study/episensor.html
  templates/case-study/esa.html
  templates/case-study/grundium-ubuntu-pro-for-devices.html
  templates/case-study/lucid-aws-fedramp-compliance-case-study.html
  templates/case-study/sbi-bits.html
  templates/case-study/ubuntu-pro-support-for-games-developer.html
Labels: Review: Code needed, Review: QA needed

#1563 feat: Set names and email as active fields on contact forms
  templates/data/postgresql/form-data.json
  templates/data/streaming/form-data.json
  templates/embedding/form-data.json
  templates/partners/silicon/intel/form-data.json
  templates/shared/forms/form-fields.html
  templates/solutions/open-source-security/cyber-resilience-act/form-data.json
  templates/solutions/telco/form-data.json
Labels: Review: Code +1, Review: QA +1

#1560 update hiring process page
  templates/careers/hiring-process/index.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1 (with changes)

#1567 fix: Modal invoke bug
  templates/macros/_macros-cta.jinja
Labels: Review: Code +1, Review: QA +1

#1531 copy: create /data/mysql/managed page. WD-17656
  requirements.txt
  templates/data/mysql/form-data.json
  templates/data/mysql/index.html
  templates/data/mysql/managed.html
  templates/data/postgresql/managed.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1, Review: Design +1

#1564 [WD-19429] migrate /edge-computing page from u.com to c.com
  static/js/modals.js
  templates/edge-computing/base_edge-computing.html
  templates/edge-computing/index.html
  templates/partners/partial/_homepage-form.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#1568 Data mysql feature
  requirements.txt
  secondary-navigation.yaml
  templates/data/mysql/form-data.json
  templates/data/mysql/index.html
  templates/data/mysql/managed.html
  templates/data/mysql/support.html
  templates/data/postgresql/managed.html
Labels: Review: QA +1

#1566 feat(case-study): add unibap space computing case study
  templates/case-study/unibap-space-computing.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1, Review: Design +1

#1537 [WD-18681] Removed toggle nav on documentation
  static/sass/styles.scss
  templates/documentation/beyond-canonical.html
  templates/documentation/index.html
  templates/documentation/open-documentation-academy.html
  templates/documentation/work-and-careers.html
Labels: Review: Code +1, Review: QA +1

#1574 chore: Update Dell logo on the Microcloud page
  templates/microcloud/index.html
Labels: Review: Code +1, Review: QA +1, Review: Design +1

#1575 Copy update: /partners/executive-summit
  templates/partners/executive-summit.html
Labels: Review: Code +1, Review: QA +1

#1571 fix(case-study): update images for the unibap case study [WD-19596]
  templates/case-study/unibap-space-computing.html
Labels: Review: Code +1, Review: QA +1, Review: Design +1

#1572 feat: Allow passing of nested index.html files to childrenPaths in the form generator
  webapp/app.py
Labels: Review: Code +1, Review: QA +1

#1556 WD-19131 Updated link in Meganav
  navigation.yaml
  templates/navigation/partials/_preview-links.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#1583 Copy update on solutions/sovereign-cloud WD-19764
  templates/solutions/sovereign-cloud/index.html
Labels: Review: Code +1, Review: QA +1

#1582 [WD-17926] copy update for opensearch
  templates/data/opensearch/what-is-opensearch.html
Labels: Review: Code +1, Review: QA +1
