Repository canonical/canonical.com, pull requests merged in 2025-05, with the labels that each got.

#1684 Copy update: /company
  templates/company/index.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#1682 copy-update: update canonical.com navigation
  navigation.yaml
Labels: Review: Code +1, Review: QA +1

#1679 [WD-21454] feat: add aria-expanded label on the contact modal trigger button at canonical.com form generator
  static/js/modals.js
Labels: Review: Code +1, Review: QA +1

#1689 fix: Replace broken links
  .github/workflows/live-links.yaml
  templates/data/kafka/index.html
  templates/navigation/navigation.html
  templates/observability/_managed-observability-modal.html
  templates/observability/_observability-modal.html
  templates/partners/partial/_homepage-form.html
  templates/shared/_client-contact-us-form.html
  templates/shared/forms/form-fields.html
  templates/solutions/ubuntu-os/index.html
Labels: Review: QA +1

#1690 copy update: update `/solutions`
  templates/solutions/index.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#1693 [WD-22013]: replace BT Group signpost logo with higher quality asset on `/solutions`
  templates/solutions/index.html
Labels: Review: Code +1, Review: QA +1

#1694 fix: Broken new links
  templates/consulting/index.html
  templates/edge-computing/index.html
  templates/navigation/navigation.html
  templates/solutions/open-source-security/index.html
Labels: Review: Code +1, Review: QA +1

#1696 fix: Failing links
  templates/data/mysql/index.html
  templates/data/postgresql/index.html
Labels: Review: Code +1, Review: QA +1

#1697 WD-22065 Remove unnecessary space before fullstop in metadata
  templates/consulting/index.html
Labels: Review: Code +1

#1702 chore: Remove deprecated JS files
  build.js
  static/js/apply-for-jobs.js
  static/js/dynamic-image-load.js
  static/js/highlight-nav-on-scroll.js
  static/js/navigation/main.js
  static/js/osselector.js
  static/js/tabs.js
  templates/careers/all.html
  templates/careers/job-detail.html
  templates/microstack/index.html
Labels: Review: Code needed, Review: QA needed

#1616 feat: rebrand and migrate dqlite.io
  secondary-navigation.yaml
  templates/dqlite/docs/document.html
  templates/dqlite/docs/search-results.html
  templates/dqlite/index.html
  webapp/app.py
Labels: Review: QA +1, Review: UX +1, Review: Design +1, Review: Code +1 (with changes)

#1695 chore: CRA copy update
  templates/solutions/open-source-security/cyber-resilience-act/index.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#1710 Update content on /careers/company-culture/diversity
  templates/careers/company-culture/diversity.html
Labels: Review: Code +1, Review: QA +1

#1706 updating text
  templates/solutions/ubuntu-os/workstations.html
Labels: Review: Code +1, Review: QA +1

#1707 [WD-21842] Refresh /careers/company-culture/remote-work
  package.json
  postcss.config.js
  scripts/build-modules.sh
  static/sass/_pattern_carousel.scss
  static/sass/styles.scss
  templates/careers/company-culture/remote-work.html
  yarn.lock
Labels: Review: Code +1, Review: QA +1, Review: UX +1, Review: Design +1

#1705 refactor: Side navigation scroll audit
  static/js/active-nav-scroll.js
  templates/documentation/beyond-canonical.html
  templates/documentation/documentation-layout.html
  templates/documentation/index.html
  templates/documentation/open-documentation-academy.html
  templates/documentation/work-and-careers.html
  templates/lxd/manage.html
  templates/solutions/index.html
Labels: Review: Code +1, Review: QA +1

#1711 copy update: update opensearch page with copydoc
  templates/data/opensearch/index.html
Labels: Review: Code +1, Review: QA +1

#1712 add missing fast track roles in careers page
  templates/careers/includes/_fast-track-jobs.html
Labels: Review: Code +1, Review: QA +1

#1713 fix: use correct form return url for /edge-computing and copy
  templates/edge-computing/index.html
Labels: Review: Code +1, Review: QA +1

#1714 [WD-18551] chore: Migrate anbox-cloud.io to canonical.com
  navigation.yaml
  secondary-navigation.yaml
  templates/anbox-cloud/form-data.json
  templates/anbox-cloud/index.html
  webapp/handlers.py
Labels: Review: Code +1, Review: QA +1

#1721 chore: run action on main repo only
  .github/workflows/sitemap.yaml
Labels: Review: Code +1

#1722 test: add tests for build_sitemap tree
  tests/test_sitemap.py
  webapp/app.py
Labels: Review: Code +1, Review: QA +1
