Repository canonical/canonical.com, pull requests merged in 2025-04, with the labels that each got.

#1621 chore: update legal section copy
  templates/contact-us.html
Labels: Review: Code +1, Review: QA +1

#1614 Valkey: Page update.
  templates/data/_database-comparison-table.html
  templates/data/mongodb/what-is-mongodb.html
  templates/data/valkey/index.html
  templates/data/valkey/what-is-valkey.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1, Review: Design +1

#1623 chore: Set up redirects for /multipass/docs and remove from codebase
  .github/workflows/pr.yaml
  navigation.yaml
  redirects.yaml
  secondary-navigation.yaml
  templates/multipass/docs/document.html
  templates/multipass/docs/search-results.html
  templates/multipass/index.html
  templates/multipass/install.html
  webapp/app.py
Labels: Review: Code +1, Review: QA +1

#1628 feat: Update sitemap parser and remove unexpected sites from being parsed
  .github/workflows/sitemap.yaml
  requirements.txt
  static/files/sitemap_tree.xml
  templates/docs/shared/_docs.html
  templates/docs/shared/_search-results.html
  templates/sitemap-index.xml
  templates/sitemap_children.xml
  templates/sitemap_tree.xml
  webapp/app.py
Labels: Review: QA +1

#1633 Update lxd installation page to recent ubuntu version and new image server
  templates/lxd/install.html
Labels: Review: Code +1, Review: QA +1

#1630 [WD-21247] Title fix for /data/streaming
  templates/data/streaming/index.html
Labels: Review: Code +1, Review: QA +1, Review: Design +1

#1647 fix: Don't purge intl-tel-input styles
  postcss.config.js
Labels: Review: Code needed, Review: QA needed

#1646 feat: Add new Java page
  templates/java/index.html
Labels: Review: Design -1, Review: QA +1, Review: UX +1, Review: Code +1 (with changes)

#1645 feat: Use sitemap templates imported from parser module
  requirements.txt
  templates/_error.tmpl
  templates/sitemap_children.xml
  templates/sitemap_template.xml
  templates/sitemap_tree.xml
  webapp/app.py
Labels: Review: Code +1, Review: QA +1

#1649 test: Implement testing for sitemap parser
  tests/test_sitemap.py
Labels: Review: QA +1

#1653 [WD-21440] - add a link to free trial
  templates/case-study/ubuntu-pro-support-for-games-developer.html
Labels: Review: Code +1, Review: QA +1

#1627 feature branch: Sitemaps parser
  .github/workflows/sitemap.yaml
  .gitignore
  Dockerfile
  requirements.txt
  templates/_error.tmpl
  templates/data/docs/index.html
  templates/docs/shared/_docs.html
  templates/docs/shared/_search-results.html
  templates/sitemap-index.xml
  tests/test_sitemap.py
  webapp/app.py
Labels: Review: QA +1

#1657 chore: Update site.yaml
  konf/site.yaml
Labels: Review: Code +1, Review: QA +1

#1659 fix: Telco form import
  templates/solutions/telco/5g-core.html
  templates/solutions/telco/5g-edge.html
  templates/solutions/telco/open-ran.html
Labels: Review: Code +1, Review: QA +1

#1660 hide second look req on cand dash
  templates/careers/application/index.html
  webapp/application.py
  webapp/utils/constants.py
Labels: Review: Code +1, Review: QA +1

#1655 Optimize GTM Loading with DOMContentLoaded to Fix GTM Delays
  package.json
  scripts/build-modules.sh
  templates/base_index.html
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#1656 [WD-21411] Add CSP header on canonical.com
  webapp/app.py
  webapp/handlers.py
Labels: Review: Code +1, Review: QA +1

#1661 chore: added more urls to CSP whitelist
  webapp/handlers.py
Labels: Review: Code +1, Review: QA +1

#1663 Update hiring video link
  templates/careers/application/index.html
Labels: Review: Code +1

#1664 Fix all the hiring videos
  templates/careers/application/index.html
Labels: Review: Code +1

#1640 Wd 20030 dev webpage webpage solutions landing page
  build.js
  navigation.yaml
  static/js/active-nav-scroll.js
  static/sass/styles.scss
  templates/solutions/form-data.json
  templates/solutions/index.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1, Review: Design +1

#1665 Dev refresh: Update Solutions nav preview links
  navigation.yaml
Labels: Review: Code +1, Review: QA +1

#1668 fix: Update sitemap action
  .github/workflows/sitemap.yaml
  konf/site.yaml
Labels: Review: Code +1

#1669 chore: Remove trailing slash
  .github/workflows/sitemap.yaml
Labels: Review: Code +1

#1658 [WD-20743] feat: new /data/lakehouse page
  templates/data/lakehouse/form-data.json
  templates/data/lakehouse/index.html
  templates/data/sitemap.xml
Labels: Review: Code +1, Review: QA +1, Review: UX +1, Review: Design +1

#1662 WD-21644 - 20.04 EOL banner
  templates/solutions/iot-and-devices/index.html
Labels: Review: Code +1, Review: QA +1

#1672 chore: Update copy of telco 5G core page
  templates/solutions/telco/5g-core.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#1676 copy update: telco/solutions
  templates/solutions/telco/index.html
Labels: Review: Code +1, Review: QA +1

#1677 chore: Add Ubuntu Pro links to navigation
  navigation.yaml
Labels: Review: Code +1, Review: QA +1

#1675 feat: Update https://canonical.com/case-study/unibap-space-computing
  templates/case-study/unibap-space-computing.html
  templates/macros/_macros-cta.jinja
Labels: Review: Code +1, Review: QA +1, Review: Design +1

#1680 Add workflow for checking broken links
  .github/workflows/live-links.yaml
Labels: Review: Code +1
