Repository canonical/canonical.com, pull requests merged in 2025-07, with the labels that each got.

#1770 feat: update /solutions/telco with two new blog links
  templates/solutions/telco/index.html
Labels: Review: Code +1, Review: QA +1

#1769 fix: migrate homepage form to form generator
  templates/contact-us.html
  templates/form-data.json
  templates/index.html
  templates/shared/forms/form-fields.html
Labels: Review: Code +1, Review: QA +1

#1771 Create a new page at /mlops/feast (WD-22833/WD-23198)
  templates/mlops/feast/form-data.json
  templates/mlops/feast/index.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1, Review: Design +1

#1774 feat: add failing form banner
  templates/base_index.html
Labels: Review: Code +1, Review: QA +1

#1725 Canonical Landing page
  .stylelintrc
  build.js
  package.json
  static/js/homepage/animations.js
  static/js/homepage/carousel.js
  static/js/modals.js
  static/js/scroll-section.js
  static/json/centre_hover.json
  static/json/cloud_icon.json
  static/json/hardware_icon.json
  static/json/silicon_icon.json
  static/json/suru_light.json
  static/json/suru_shadow.json
  static/sass/_pattern_careers-progression.scss
  static/sass/_pattern_homepage.scss
  static/sass/styles.scss
  templates/index.html
  webapp/handlers.py
  yarn.lock
Labels: Review: Code +1, Review: QA +1, Review: UX +1, Review: Design +1

#1786 Bugfix: WD-23663 Replaced correct asset on solutions page
  templates/index.html
  templates/solutions/index.html
Labels: Review: Code +1, Review: QA +1

#1789 copy update: solutions/financial-services
  templates/solutions/financial-services/index.html
Labels: Review: Code +1, Review: QA +1

#1790 feat: Add maas discourse API keys
  konf/site.yaml
Labels: Review: Code +1

#1788 Bugfix:(WD-23689) Color change on hover on disabled button
  static/sass/_pattern_homepage.scss
Labels: Review: Code +1, Review: QA +1

#1772 feat: Migrate maas.io to /maas
  package.json
  postcss.config.js
  scripts/build-modules.sh
  secondary-navigation.yaml
  static/sass/_maas_styles.scss
  static/sass/_pattern_strip.scss
  static/sass/_pattern_venobox.scss
  static/sass/styles.scss
  templates/blog/article.html
  templates/maas/_tutorial.html
  templates/maas/contact-us.html
  templates/maas/docs/base_docs.html
  templates/maas/docs/document.html
  templates/maas/docs/search-result.html
  templates/maas/how-it-works.html
  templates/maas/index.html
  templates/maas/resources.html
  templates/maas/tour.html
  templates/maas/tutorials.html
  webapp/app.py
  yarn.lock
Labels: Don't merge, Review: Code +1, Review: QA +1

#1797 feat: Update source reference on /solutions/financial-services
  templates/solutions/financial-services/index.html
Labels: Review: Code +1, Review: QA +1

#1800 Update deploy.yaml
  .github/workflows/deploy.yaml
Labels: Review: QA +1

#1802 add anchore logo to solutions page
  templates/solutions/index.html
Labels: Review: Code +1, Review: QA +1

#1803 Update ISSUE_TEMPLATE.md, add a note about security advisory
  .github/ISSUE_TEMPLATE/ISSUE_TEMPLATE.md
Labels: Review: Code +1

#1801 [new page] WD-23241 - feat: create solutions/automation page
  navigation.yaml
  package.json
  static/js/tabbed-content.js
  static/sass/styles.scss
  templates/careers/hiring-process/index.html
  templates/consulting/index.html
  templates/solutions/automation/form-data.json
  templates/solutions/automation/index.html
  templates/solutions/financial-services/index.html
  templates/solutions/telco/index.html
  yarn.lock
Labels: Review: Code +1, Review: QA +1, Review: UX +1, Review: Design +1

#1576 [WD-19329] Copy update c.com/openstack
  redirects.yaml
  secondary-navigation.yaml
  templates/openstack/architecture.html
  templates/openstack/index.html
Labels: Review: Code +1, Review: QA +1

#1805 feat: fix blocked cookie policy
  scripts/build-modules.sh
  templates/base_index.html
Labels: Review: Code +1, Review: QA +1

#1809 [WD-23691] fix: Newsletter 'sign up' buttons goes blank when clicked
  static/js/forms.js
Labels: Review: Code +1, Review: QA +1

#1810 feat: add autocomplete attributes to form elements in form-generator template
  templates/shared/forms/form-fields.html
Labels: Review: QA +1

#1812 [WD-24062] feat: mandatory contact fields on form generator
  templates/anbox-cloud/form-data.json
  templates/consulting/form-data.json
  templates/data/lakehouse/form-data.json
  templates/data/mysql/form-data.json
  templates/data/postgresql/form-data.json
  templates/data/streaming/form-data.json
  templates/form-data.json
  templates/mlops/feast/form-data.json
  templates/openstack/form-data.json
  templates/partners/silicon/intel/form-data.json
  templates/shared/forms/form-fields.html
  templates/solutions/automation/form-data.json
  templates/solutions/automotive/form-data.json
  templates/solutions/cloud-native-development/form-data.json
  templates/solutions/data-and-ai/form-data.json
  templates/solutions/financial-services/form-data.json
  templates/solutions/form-data.json
  templates/solutions/industrial/form-data.json
  templates/solutions/iot-and-devices/form-data.json
  templates/solutions/open-source-security/cyber-resilience-act/form-data.json
  templates/solutions/telco/form-data.json
Labels: Review: Code +1, Review: QA +1

#1814 [WD-24063] fix: modal form not opening on canonical.com/solutions/cloud-native-development
  static/js/tabbed-content.js
Labels: Review: Code +1, Review: QA +1

#1808 Migrate maas.io/docs/api & maas.io/support
  redirects.yaml
  templates/maas/docs/_api.html
  templates/maas/support.html
  tests/openapi_example.yaml
  tests/test_openapi_parser.py
  webapp/app.py
  webapp/openapi_parser.py
Labels: Review: Code +1, Review: QA +1

#1813 feat: updated readme
  .github/workflows/deploy.yaml
Labels: Review: QA +1

#1815 feat: Refresh /public-sector
  templates/public-sector/index.html
  templates/solutions/industrial/index.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1, Review: Design +1
